### ISSUE TITLE
Transient issues spinning up servers related to pod reflector errors

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1103]
### Context

We often get support tickets along the lines of "can't spin up a user server" that appear to be transient in nature. Upon inspection of the logs, we see `pod reflector errors` which can be caused either by a k8s master API outage, or a race condition in the hub.

I have opened an issue in the jupyterhub/grafana-dashboards repo to ask for the k8s master API stats to be included since this will help us debug these types of issue: https://github.com/jupyterhub/grafana-dashboards/issues/34

Deleting the hub pod and allowing it to be recreated should help things if it was a race condition in the hub too.

Specifically, the pilot-hubs cluster is zonal, not regional, which means it's k8s master API is not highly available and is therefore more prone to these issues. See https://github.com/2i2c-org/infrastructure/issues/1102

### Actions and updates

- [ ] Resolve https://github.com/2i2c-org/infrastructure/issues/1055
- [ ] Check whether this solved our problem (which will probably require just noticing whether this behavior pops up over time)

**Comment by yuvipanda** [comment]
I've bounced (aka restarted) all the hub pods on the pilot-hubs cluster with this line:

```
kubectl get ns | choose 0 | rg -v aup | xargs -L1  kubectl  delete pod -l component=hub -n    
```

[choose](https://github.com/theryangeary/choose) is an awesome alternative to `cut` or `awk`, and rg is [ripgrep](https://github.com/BurntSushi/ripgrep) an awesome alternative to grep. I skipped `aup` because I had already restarted that hub pod, and didn't want to do it again.

**Comment by yuvipanda** [comment]
In this case, I think restarting the hub was the right call - I think we were just seeing https://github.com/jupyterhub/kubespawner/pull/525 again. I see the following line in the log:

```
[C 2022-03-15 03:26:39.979 JupyterHub spawner:2222] Pods reflector failed, halting Hub.
```

But the hub does not halt :) 

I think what happened is:

1. k8s api had some downtime / latency issues
2. hub's reflectors failed multiple times during this, causing kubespawner to decide it needs to shut itself down
3. This triggers https://github.com/jupyterhub/kubespawner/pull/525, leaving the hub in a zombie state.

Restarting the pods fixes this, and upgrading to latest z2jh (which has https://github.com/jupyterhub/kubespawner/pull/525 in it) will fix this for good.

**Comment by yuvipanda** [comment]
I think upgrading z2jh will help fix this.

**Comment by choldgraf** [comment]
Just noting that this issue is tracking upgrading Z2JH / JupyterHub to 2.0 (though maybe you're suggesting we upgrade to a later 1.x branch?

- https://github.com/2i2c-org/infrastructure/issues/1055

**Comment by yuvipanda** [comment]
@choldgraf nope, 2.x should fix it.

**Comment by choldgraf** [comment]
@yuvipanda awesome, I've updated the top comment to clarify the next steps here

**Comment by choldgraf** [comment]
Just noting that we have another incident related to this issue:

- #1135

It looks like we can't solve this for good until z2jh 2.0 is released. Since this has become a fairly common problem, as a stopgap maybe we can share the actions that often resolve this problem in the top comment of this issue (or somewhere else?)

It seems like the easiest thing is to restart the hub pod, and it then works ok when it comes back. Is that right?

**Comment by sgibson91** [comment]
> It seems like the easiest thing is to restart the hub pod, and it then works ok when it comes back. Is that right?

Yes

**Comment by yuvipanda** [comment]
@choldgraf we don't need to wait for z2jh 2.0 (which will involve other work to upgrade) to get this fixed, as there's a released version of kubespawner with the fix. https://github.com/2i2c-org/infrastructure/pull/1137 should fix this.
