### ISSUE TITLE
Add a Grafana plot to monitor disk usage on the home directory

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1119]
### Background and proposal

In https://github.com/2i2c-org/infrastructure/issues/1081 we had a hub outage because the cluster had run out of disk space, causing user launches to fail.

Running out of disk space is a common concern for our hubs, and we should set up a Grafana plot so that we can monitor and potentially send alerts when disk space is low.

### Implementation guide and constraints

There are two related issues here, and we may want to solve them independently if need be:

- First, have a plot that shows disk space usage / remaining on a cluster. This could be an upstream contribution in https://github.com/jupyterhub/grafana-dashboards
- Second, add an alert for this, ref: https://github.com/2i2c-org/infrastructure/issues/328

**Comment by sgibson91** [comment]
This may be a useful issue to move upstream? https://github.com/jupyterhub/grafana-dashboards

**Comment by yuvipanda** [comment]
This is a bit complicated on Azure or AWS since we're using managed storage service (AzureFile or EFS), and we'll need an exporter specifically for those that prometheus can scrape.

**Comment by choldgraf** [comment]
@yuvipanda aren't we also planning to move to Google's managed filesystem service as well?

**Comment by damianavila** [comment]
> Curious if you find it useful.

I think it provides useful information. The second one is a per-user usage rate, correct?

**Comment by choldgraf** [comment]
These all seem useful to me as well - I am curious what "daily usage" means though, does it mean "data written to disk"?

**Comment by GeorgianaElena** [comment]
As I mentioned, the graphs are ported from https://grafana.com/grafana/dashboards/11454 and not my creation, but the query that generates that graph is `rate(kubelet_volume_stats_used_bytes[1d]`).

Didn't find any official docs for `kubelet_volume_stats_used_bytes` other than [these](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/collectors/volume_stats_test.go#L48).

So, from what I understand, the daily usage graph shows the daily bytes usage rate in a particular volume. And yes, I believe each of the prod (home-nfs) there corresponds to a user. And since the home-nfs PVs have a retain policy, they don't ever get destroyed.

**Comment by consideRatio** [comment]
This is done!

**Comment by damianavila** [comment]
> This is done!

I think this is the proper ref: https://github.com/2i2c-org/infrastructure/pull/1992
