### ISSUE TITLE
[UTexas] Sidecar database container malfunction for an individual user

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1261]
A user in the UTexas hub has their sidecar PostgreSQL container failing to start or similar: https://2i2c.freshdesk.com/a/tickets/127

## Action points

- Investigate and try to figure out the reason for the failure
- If possible solve it
- Communicate back

**Comment by GeorgianaElena** [comment]
### Update
Checking the logs of the `postrgres` container for the user that reported issues showed the following error:

```
 PANIC:  could not write to file "pg_wal/xlogtemp.14": No space left on device
```

Which probably means that the `postgres` server can't start because of the lack of space, which seems to be confirmed by the fact that that the `postgress-{username}` volume is almost full.

### Possible solutions

1. Manually resize the disk for this particular user to fix the issue -> but this would create inconsistencies with the infra repo

2. Ask the user to delete some data from the db to free up some space

3. Resize the db disks for all the users from 1GB to 2GB ([code ref](https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/2i2c/utexas.values.yaml#L50))

**Comment by consideRatio** [comment]
I think asking the representative makes sense here. I see their options as: 
1. they can ask their user to clear some space on their disk,
2. or, they ask that we increase limits for all users to X GB from 1GB.

The option of asking us to manage insividual users disk space seems possibly unsustainable and is an option ill suggest we dont propose at this point.

Long term, allowing users etc to see their storage space quota etc would be very helpful. Then, a user may figure out right away something would be wrong due to max storage.

**Comment by yuvipanda** [comment]
We mount the postgres database storage in the user's container too - https://github.com/2i2c-org/infrastructure/blob/f52a643e8e27ddbd2cbf0a64334fd025f36f5ce8/config/clusters/2i2c/utexas.values.yaml#L79. They *should* have enough permissions to delete it all themselves. `df -h` on a terminal *should* show them quota info but I agree this should be far more visible.

**Comment by choldgraf** [comment]
Note that @jameshowison actually suggested in the FreshDesk ticket that they'd need significantly more than 2GB - more like 10GB I believe. So it sounds like the limit that's there just about an order of magnitude too small?

**Comment by yuvipanda** [comment]
Looking at https://cloud.google.com/compute/disks-image-pricing#disk, it's about 0.04GB per GB per month. So if there are ~40 students, and we give them all 10G that's about a 16$ increase in monthly cost. So let's just do it?

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/1262 just increases this to 10G

**Comment by choldgraf** [comment]
@yuvipanda this makes sense to me - that is not a significant amount of money, and this increase in size will only be needed for one week or so. I'm +1 on doing it.

**Comment by csst-sociotech** [comment]
UTexas Hub is down this morning, showing "500: Internal Server Error"

**Comment by GeorgianaElena** [comment]
Thanks for reporting this @csst-sociotech! We're currently investigating the problem

**Comment by GeorgianaElena** [comment]
@csst-sociotech, server spawning should be working again now. Can you please confirm that it works for you?
