### ISSUE TITLE
Matlab integration for Openscapes 2i2c Hub

### ISSUE THREAD

**Issue by erinmr** [2i2c-org/infrastructure#1321]
### Context

Hi - We are working with some of our NASA Champions who are starting with Matlab and trying to migrate to Python. We have been using AWS directly for this group, but it isn't easy to use and makes the distance for these users trying to learn Python even further. I know that Matlab isn't open. We are taking the approach of starting with where people are and helping them use the cloud from there.  

### Proposal

Would our hub allow this matlab integration? [](https://github.com/mathworks/jupyter-matlab-proxy ) When I try to do this, i get an error that I need node.js. Thanks so much for any guidance - Erin

**Comment by colliand** [comment]
Hi Erin! Thanks for your message. In the future, I suggest that messages like this be shared through 2i2c's support channel. That will likely generate a faster response.

Our engineering team discussed this request today. It is technically possible to deliver Matlab via JupyterHub. This [repo from MathWorks](https://github.com/mathworks/jupyter-matlab-proxy) provides some guidance. Based on our discussion, I suggest three paths forward for Openscapes:

1. Openscapes adds Matlab to the image that defines the resources available on Openscapes' JupyterHub.
2. 2i2c assists Opescapes with adding Matlab to Openscapes' JupyterHub.
3. Consider [GNU Octave](https://www.gnu.org/software/octave/index)?

While 2i2c champions open source software, there is no "open source purity" test that prevents us from delivering Matlab. Our strategy is to deploy JupyterHub, as specified in the partner's image, using cloud infrastructure consistent with the [Right to Replicate](https://2i2c.org/right-to-replicate/). This strategy separates the image (what software is delivered to users) from the infrastructure (the way the software is delivered using cloud and JupyterHub). 

The image is yours to specify! This leads to the first path above. For path 2, 2i2c can potentially provide assistance in constructing and deploying the image. Doing that work will require some scoping and will involve development costs. (Let us know if you'd like us to develop an work plan and cost estimate.)

On Path 3....Octave is "drop-in compatible with Matlab scripts" and there is an Octave kernel for Jupyter. The usage scenario for Matlab would enable users to launch into the Matlab GUI from the landing page after logging into the hub. The usage scenario for Octave would enable users to run Matlab-like code inside JupyterLab or Jupyter Notebook. The Octave-in-Jupyter path has the potential to bring users into the "Let's use Jupyter collaboratively because of open science, etc." vibe while allowing them to make first steps using "drop-in compatible" Matlab code.

I welcome discussion. If you wish to discuss synchronously, please reach out!

**Comment by erinmr** [comment]
thanks so much for this response - I will use the support channel in the future. I think options 1 and 3 will work for us to start. I will share Octave with our developer too. If we need more help I'll circle back.

**Comment by yuvipanda** [comment]
@erinmr I think this was done, right? Can you tell us what the eventual outcome here was?

**Comment by erinmr** [comment]
Hi @yuvipanda - Thanks for checking in. This is working. We haven't done much experimentation with it because our group's interest hasn't been around Matlab analysis. My limited use was that it was a big improvement from needing to spin up a virtual machine every time I wanted to use Matlab on AWS. Thanks for helping us with this!

**Comment by yuvipanda** [comment]
@erinmr yay, awesome! Glad it is useful :) I'm going to close this issue as done :)
