### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1431]
### Link and reference warnings

**Configuration error**
- 

**There is a programmable error in your configuration file**
- 

**Warning**
- 

**Traceback (most recent call last)**
- 

**Warning**
-   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sphinx/config.py", line 332, in eval_config_file

**Warning**
-     exec(code, namespace)

**Warning**
-   File "/home/runner/work/infrastructure/infrastructure/docs/conf.py", line 180, in <module>

**Warning**
-     render_tfdocs()

**Warning**
-   File "/home/runner/work/infrastructure/infrastructure/docs/conf.py", line 168, in render_tfdocs

**Warning**
-     subprocess.check_call(

**Warning**
-   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 368, in check_call

**Warning**
-     retcode = call(*popenargs, **kwargs)

**Warning**
-   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 349, in call

**    with Popen(*popenargs, **kwargs) as p**
- 

**Warning**
-   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 951, in __init__

**Warning**
-     self._execute_child(args, executable, preexec_fn, close_fds,

**Warning**
-   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 1821, in _execute_child

**Warning**
-     raise child_exception_type(errno_num, err_msg, err_filename)

**FileNotFoundError**
-  [Errno 2] No such file or directory: 'terraform-docs'

**Comment by sgibson91** [comment]
Is.... is this issue/an action working the way it's supposed to? 😳

**Comment by damianavila** [comment]
@choldgraf might know better, but I think it does... but wondering why you are asking about it?

**Comment by damianavila** [comment]
> but wondering why you are asking about it?

Well, I have seen this one working as expected in other repos... not sure about this one, particularly.

**Comment by damianavila** [comment]
> I feel like some automated process has overwritten what the original top comment said?

Most likely the case...

**Comment by sgibson91** [comment]
I guess I wasn't sure if that was intentional or not, have we lost some context because something was overwritten, is it a bug that something here was overwritten? I just happened to come across this the other day and it was confusing that discussion didn't seem relevant to the top comment.

**Comment by damianavila** [comment]
The previous versions of the original message could be seen in the top comment (using the dropdown arrow). In this case, I believe the overwritten is just a one-off error because the implementation changed at some time during the above discussion. I think I am going to close this one and let the bot raise a new clean issue the next time it runs, so we are sure things are working as expected (as it seems in other repos).

**Comment by damianavila** [comment]
For additional context, this is the original text at the top comment:

# Context
Currently, [we use this github workflow](https://github.com/2i2c-org/infrastructure/blob/master/.github/workflows/doc-links.yml) to run a linkcheck of our documentation on each pull request. This generates a decent amount of PR noise as links fairly often break in ways that are un-related to the PR.

# Proposal
Instead of running this workflow on each PR, we could instead do something like the following:

Open an "One or more links are broken in our documentation" issue. This is a generic issue we'll re-use forever for any broken docs links.
Every day on a CRON job, run the linkcheck workflow
If a link is broken, collect the link and update the top comment of the issue above with the new broken link.
If the issue was closed, re-open it.
When we fix the link, we should close that issue via the PR
I think that this would reduce the number of broken tests for our infrastructure changes, but still allow us to track when our docs links have become out of date.

# Updates and actions
No response
