### ISSUE TITLE
Automatically run script to clone a git repo on user server startup

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1536]
### Context

This is a requirement for the upcoming event #1300.

In https://2i2c.freshdesk.com/a/tickets/155, Ariel Rokem asks that the hub is configured in a way so that user pods starting will automatically run a script doing a certain thing - namely using gitpuller CLI from nbgitpuller python package to clone a fresh repo into a folder.
It may merit some discussion on how to do that technically. 

### Proposal 
@consideRatio describes how he did it earlier in https://github.com/2i2c-org/infrastructure/issues/1505#issuecomment-1183375652 - using a k8s lifecycle postStart hook and a script he had mounted via the Helm chart but now can be provided via singleuser.extraFiles functionality as hub specific configuration.

### Updates and actions

This can be approached in various ways, depending on how we expect/want to use in the future, in the context of other hubs too. The list below aggregates multiple great options from people that we can choose from:

➡️ 1.  We provide script files via singleuser.extraFiles, and we configure a postStart hook to run one script on startup
➡️ 2.  We configure an initContainer to run the script
➡️ 3.  We provide script files via singleuser.extraFIles, but we don't configure a postStart hook to run one script on startup
➡️ 4. We ask that Ariel provide script files via the Dockerfile and that users are provided instructions to run a script from the terminal and/or use a nbgitpuller link to get setup initially, as that de-couples 2i2c from adding customization for this hub beyond what has been done for other hubs.
➡️ 5. We ask that Ariel provide script files via the Dockerfile and run a [Jupyter Docker Stack start-up hook](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) to execute it
➡️ 6. We make the defaultUrl be a pointer to the nbgitpuller URL? That way, users can login to the hub and it'll treat them exactly like they clicked the nbgitpuller url
➡️ 7.

**Comment by consideRatio** [comment]
The approach of using a postStart lifecycle hook is a bit problematic and I wanted to highlight that so it doesn't come as a surprise later.

If a [k8s `postStart` lifecycle hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) fail, it means pod startup will be considered failed. So, if the script does something like accessing a github repo, and github is intermittently down - the script can fail, and the user pod startup fails.

Due to this, use of `postStart` lifecycle hooks should be adopted with some caution.

Also, when you develop the logic running in the hook, they won't be emitting logs on successful runs. So if you want to debug them, you must write out traces to disk for later inspection. If they error, one can use `kubectl describe pod` to see the events associated with the pod, and there will be an k8s Event associated with the pod listed there including `stderr` and `stdout` i think.

**Comment by damianavila** [comment]
So... more in favor of the `singleuser.extraFiles` option...

**Comment by damianavila** [comment]
cc @GeorgianaElena, I would be she will be interested because she deployed this hub in https://github.com/2i2c-org/infrastructure/pull/1507.

**Comment by GeorgianaElena** [comment]
> So... more in favor of the singleuser.extraFiles option...

I believe the `singleuser.extraFiles` is just an alternative to make the script available in the singleuser pod rather than an alternative on how to run it.

I have two questions that will help me better understand things. @consideRatio, maybe you can help me? ✨ 

1. This script should do the same thing nbigitpuller does, but automatically, without the users clicking any ngbitpuller links? If so, do you know which advantages has this? I guess there's  the obvious one of having everything there and ready right from the start?
2. Could running this script in an `initContainer` make sense?

**Comment by consideRatio** [comment]
> I believe the singleuser.extraFiles is just **an alternative to make the script available in the singleuser pod rather** than an alternative on how to run it.

Yes 100%, this is a matter of both providing the relevant logic to execute, and having a way to execute it!

---

> This script should do the same thing nbigitpuller does, but automatically, without the users clicking any ngbitpuller links? If so, do you know which advantages has this? I guess there's the obvious one of having everything there and ready right from the start?

Yepp, options could be to ask users to click the nbgitpuller-link and/or to run a command in the terminal whenever they wanted it updated.

Here are options I think all are reasonable:

1. We provide script files via singleuser.extraFiles, and **we configure** a `postStart` hook to run one script on startup
2. We provide script files via singleuser.extraFIles, but **we don't configure** a `postStart` hook to run one script on startup
3. We ask that Ariel provide script files via the Dockerfile and that users are provided instructions to run a script from the terminal and/or use a nbgitpuller link to get setup initially, as that de-couples 2i2c from adding customization for this hub beyond what has been done for other hubs.

An option to 1 is to use an initContainer as well, and that would improve debuggability overall, but a failure there would also be crashing the startup of the pod. If configuration of an initcontainer is considered, note that I think basehub already configures the user pods init containers to chown files etc - adding it here could be tricky because lists are overriding each other rather than appending if configured in two locations.

I think it would be good if several people in @2i2c-org/tech-team considered this, and that if option 1 or 2 is chosen, that its communicated as something that isn't meant to change so often as it requires an intervention from 2i2c tech team as compared to if it was script etc provided via a Dockerfile that the hub representative could manage.

**Comment by yuvipanda** [comment]
How about we make the defaultUrl be a pointer to the nbgitpuller URL? That way, users can login to the hub and it'll treat them exactly like they clicked the nbgitpuller url

**Comment by yuvipanda** [comment]
And if there is a GitHub failure or anything, it just shows the nbgitpuller error page with useful info. They can also click out to go to lab / notebook

**Comment by damianavila** [comment]
> We ask that Ariel provide script files via the Dockerfile and that users are provided instructions to run a script from the terminal and/or use a nbgitpuller link to get setup initially, as that de-couples 2i2c from adding customization for this hub beyond what has been done for other hubs.

What about running a [Jupyter Docker Stack start-up hook](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) if we want to automate this one?
This option would avoid the pod post-start hook and keep this customization in the userland.

**Comment by jmunroe** [comment]
Will the design for this feature allow for more than one repo to be pulled? Or is it restricted to choosing just one?

I ask because I am thinking about more generic 2i2c "starter" material that could be pulled from git *in addition* to any community specific notebooks that need to made available.

**Comment by GeorgianaElena** [comment]
I've updated the `Updates and actions` section in the top comment with all the proposals here. Thanks everyone

### My opinion

I believe all the proposals here are very valuable and they all make sense ❤️ 

But each of them comes with their own pros and cons and open up the gate to various possible new features and use cases. So, I believe choosing between them is a matter of thinking what use-cases we want to support for our hubs and then decide upon an implementation based on what tradeoffs we're willing to do.

### My suggestion - short term
Since this was essentially opened as a follow-up to a support ticket requesting a new feature for an event that's due next week, I suggest focusing on that use-case first.

For this particular event, I believe @yuvipanda's suggestion of using `defaultUrl` to point to an nbigitpuller link makes more sense because:
- doesn't require infrastructure changes
- is quick
- it does the job
- issues with it might be easier to debug
- doesn't force us make a decision now about the longer term plan ⬇️

### My suggestion - long term

But on the longer run, I believe we need to answer some questions before choosing the right technical implementation:
#### Questions to answer:

- Do we want for our hubs to be able to provide the feature of having user pods automatically run a script doing a "certain thing" when starting?
- Do we want the "certain thing" be one thing or be extensible to "more things"?
- Do we want us to be the ones being able to perform this super power or do we want to offer it to the communities?

### Conclusion
1. We go with the shorter term solution for now
2. We continue pushing the conversation further to decide upon a longer term solution, either in this issue or we open up a new one. I also like @jmunroe's suggestion of thinking of https://github.com/2i2c-org/infrastructure/issues/1549 as a possible use-case for this feature and we should take that into account too.

What does the @2i2c-org/tech-team think?

**Comment by GeorgianaElena** [comment]
Then, @arokem do you want to install [`nbgitpuller`](https://github.com/jupyterhub/nbgitpuller) into the user image so we can give ⬆️ a try? ✨

**Comment by arokem** [comment]
Should be installed now!

**Comment by arokem** [comment]
Hi! Is this now implemented in the hub? Otherwise, do you have a sense of the timeline for this to be implemented? The event starts on Monday, so if we don't anticipate having it implemented by Tuesday morning, we'll need to come up with another plan for how to have participants access these materials.

**Comment by sgibson91** [comment]
@arokem As soon as https://github.com/2i2c-org/infrastructure/pull/1552 is merged, you're good to go.

**Comment by arokem** [comment]
Aha gotcha! With apologies, I did not have notifications about that PR. Looks like it just got merged 🎉

**Comment by GeorgianaElena** [comment]
I've just merged the PR @arokem! Once the deploy finishes, the nbigitpuller redirect should show up on server start-up. Once the repo is pulled, then the user will be redirected to `/lab` in the directory containing the repo contents, i.e. `nh2022-curriculum`.

Small note about this though: any changes to the default interface through the configurator, will overwrite the `nbgitpuller` link that we've set.

I have to log off to tonight however. But can the @2i2c-org/tech-team on the other side of the world help out if any issue with https://github.com/2i2c-org/infrastructure/pull/1552 shows up? Thank you ✨

**Comment by arokem** [comment]
OK - looks like we're back online and nbgitpuller is working as expected. Thanks!

**Comment by GeorgianaElena** [comment]
Sorry for the disruption @arokem, but I noticed the nbgitpuller defaultUrl setup didn't work as expected in the first time.
So I've tried a bunch of other things and ended up opening https://github.com/2i2c-org/infrastructure/pull/1557 and manually deployed it.

This should have been done the trick and the nbgitpuller option should show up in the configurator.

**Comment by arokem** [comment]
Yes. I see this option in the configurator now. This works fine! 

Tiny adjustment request is that I would prefer it if the launch directory of the lab interface was `~/` instead of (as currently configured) `~/nh2022-curriculum`.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/1557 I left some suggested comments there to make the user launch into ~.

Thanks a lot for figuring this out, @GeorgianaElena!!!

**Comment by GeorgianaElena** [comment]
I suggest closing this issue since was framed as a support request rather than an enhancement proposal and we've already implement it for the neurohackademy hub.

We can track the https://github.com/2i2c-org/infrastructure/issues/1549 aspect of it in the said issue and maybe resurface this if we decide to support "running a script on user server startup" as a feature.

Please, feel free to reopen if you disagree
