### ISSUE TITLE
Enable access to GPUs for the meom-ige hub

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1592]
### Context

GPU access was requested for the `meom-ige` hub in https://2i2c.freshdesk.com/a/tickets/167.

### Proposal

From what I can tell from https://github.com/2i2c-org/infrastructure/blob/master/terraform/gcp/projects/meom-ige.tfvars, it looks like gpu is not enabled.

### Updates and actions

We have docs about gpu support for aws clusters here -> https://infrastructure.2i2c.org/en/latest/howto/features/gpu.html, but meom-ige runs on GCP. But this might be a good opportunity to document this for gcp provider too.

**Comment by sgibson91** [comment]
Also, the meom-ige cluster is deployed in `us-central1-b`. We tend to use `us-central1-c` for GPUs since there is better availability in that zone. However, migrating will cause an outage as it has to be torn down and redeployed, so we should double check with them that that is acceptable.

I'm also not sure how that migration would affect the filestore, if the homedirs would be moved across or wiped. So we should advise them to backup anything they need from the hub beforehand.

**Comment by auraoupa** [comment]
Hi, Thanks for opening the request ! I was primarily just wondering if it was already done (so the answer is no) and secondly if it could be added simply : it looks like it would shake things up a bit too much. I'll have to check with the rest of the users if it is really needed and that will take some time as August is very slow in France ... I may come back here in September with new details then !

**Comment by yuvipanda** [comment]
@auraoupa just wanted to check-in - is this still desired? :)

**Comment by auraoupa** [comment]
Hi @yuvipanda, no need for GPU anymore, thanks for checking !

**Comment by yuvipanda** [comment]
Thanks for letting us know, @auraoupa!
