### ISSUE TITLE
Iterate on docs for log inspection

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1692]
## Updated October 2023

We have https://infrastructure.2i2c.org/howto/troubleshoot/logs/# that includes log inspection docs for GCP specifically, with examples on [looking at hub logs](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-hub-logs) and [looking at user pods](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-a-specific-user-s-logs).

We should have docs about `kubectl`, and at least summarize the status of inspecting logs in our AWS and Azure clusters even if it is "we can't" or similar.

## Action points

- [ ] Provide docs building them out from [these](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-hub-logs) on using `kubectl` to look at logs.
  - `kubectl logs` is cluster a cluster agnostic choice great to use if it works
  - Include notes about `--previous`, `--since=1h`, `--tail`, and `--follow`
- [ ] Validate the documented log examples for GCP logging since they recently changed their UI
- [ ] Explore the status of logs collection in EKS and document the findings
- [ ] Explore the status of logs collection in AKS (utoronto) and document the findings

<details>

<summary>Original issue</summary>

### Context

One of the most common things that we need to do is check the JupyterHub logs when there is an error. Doing this requires accessing the cloud infrastructure via the shell, but I don't believe it is documented in our infrastructure docs. For example, here's a search for `logs`:

https://infrastructure.2i2c.org/en/latest/search.html?q=logs

### Proposal

We should add a section to our documentation that is easily searchable that provides how-to information for how to access the hub logs. E.g. `## How to access the hub logs` with a step-by-step list to follow.

</details>

**Comment by sgibson91** [comment]
We should also document the method of accessing logs that I pointed out here https://github.com/2i2c-org/infrastructure/issues/1617#issuecomment-1211741192

That method:

1. Does not require command-line access, only GCP project access
2. Provides more historical logs. If the hub pod is restarted, you may lose some logs - but they will be retained in the GCP project.

Hence, I think that method should be the source of truth. That is what we used to track down the API master issue as that was happening over such a long timeframe, it wasn't practical to view those logs in the command line.

**Comment by sgibson91** [comment]
I also think it would be useful to document some basic searches of the GCP Logs archive that are good things to try when faced with an incident

**Comment by consideRatio** [comment]
I'm trying to narrow the scope to be very clear about the work to be done.

Here are some points:
- To document how to access hub logs via `deployer use-cluster-credentials <cluster>` + `kubectl logs -n <hub> deploy/hub -c hub [--previous]`
- To clarify and document how to access logs from a pod's container via various cloud consoles, with examples on how to access a specific hub pod and user pod based on labels
  - GCP (doable)
  - AWS (is this doable? I'm not sure if logs are retained atm.)
  - Azure (Is this doable? I don't think they retain logs because utoronto has a thing writing logs to a persistent disk.)

I consider us actionable with documeting logging with `kubectl` and GCP.

Looking at our docs, I find that we have https://infrastructure.2i2c.org/howto/troubleshoot/logs/# that includes a lot for GCP specifically, with examples on [looking at hub logs](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-hub-logs) and [looking at user pods](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-a-specific-user-s-logs).

## Action points

- [ ] Provide docs building them out from [these](https://infrastructure.2i2c.org/howto/troubleshoot/logs/#look-at-hub-logs) on using `kubectl` to look at logs.
  - `kubectl logs` is cluster a cluster agnostic choice great to use if it works
  - Include notes about `--previous`, `--since=1h`, `--tail`, and `--follow`
- [ ] Validate the documented log examples for GCP logging since they recently changed their UI
- [ ] Explore the status of logs collection in EKS and document the findings
- [ ] Explore the status of logs collection in AKS (utoronto) and document the findings
