### ISSUE TITLE
Custom jupyter-server templates

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1697]
### Context

Currently we are able to provide custom templates for the hubs through https://github.com/2i2c-org/default-hub-homepage.

But a recent request to customize the look of  the single user's server from https://github.com/2i2c-org/infrastructure/issues/1439#issuecomment-1238790781 generated this issue.

Do we want to provide customizations for [`jupyter-server` templates](https://github.com/jupyter-server/jupyter_server/tree/main/jupyter_server/templates)? If so, where should we host this custom templates:? 
- in a new repo similar to https://github.com/2i2c-org/default-hub-homepage
- or in the same one?

**Comment by damianavila** [comment]
@GeorgianaElena come up with a compromised solution in #1710.

> But as I mentioned in the comments above, this implementation is a compromise. This was my own take on making this to work given the available time and feedback (at that time I considered this to be a time sensitive request, but turns out it wasn't).

In that PR I raised this comment:

> Regardless of the specifics of the implementation, I have the feeling we are entering into the user image territory... It should relatively easy for them to self-serve the customization of the templates on the user image itself, right?

When I saw the problem I was immediately thinking about customization of the templates at the user image level.
Now re-reading the first message of this thread, I understand there might be a second option to allow community customization but still own the template repo as we do with the [default-hub-homepage](https://github.com/2i2c-org/default-hub-homepage).

I am still not convinced about the second option because the `tree` and `notebook`, IMHO, belong to the user territory but happy to be convinced otherwise :wink.

**Comment by GeorgianaElena** [comment]
It is possible to use [singleuser.extraFiles config](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extrafiles) to customize certain jupyter templates. That is not suitable for complex UIs, but since we weren't requested to make complex changes, let's close this and reopen/open a new issue when/if this will be needed.
