### ISSUE TITLE
Match the `New Hub` Issue Template with current workflow

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1734]
### Context

Initially, the new hub issue was designed to be filled in by a community representative. But right now, this template is actually used by a 2i2c member instead.

This has generated new hub issues, where the actual information from the community representatives is gathered in follow-up comments and not encompassed in the top level form.

This makes it hard for someone in the engineer team (or at least it is for me) to follow up the entire thread to get the required info.

Equally, after reading the thread if you want to extract any useful info into the top level comment, you need to edit it in it's raw form, instead of taking advantage of the nice Issue form from GitHub.

### Proposal

We should match the issue template to our current workflow.

I suggest we split the new hub issue template into two:

 -  One template is for the 2i2c members that "translate" leads issues into new hub requests
  - One template is meant as before: to be a form for the community representative to fill.

Questions and a free form communication should happen in the first type of issue, and the community rep only fills in the new hub form when they have all the info they need. This will then be used to deploy the new hub.

**Comment by damianavila** [comment]
Parent and a more general issue live at #450.

But let's scope this one to accommodate (and improve a little bit) the existing situation

> We should match the issue template to our current workflow.

as @GeorgianaElena says above.

> I suggest we split the new hub issue template into two:

I agree (partially, see my comments below).

> One template is for the 2i2c members that "translate" leads issues into new hub requests

This is where we might change things a little bit and maybe have a Google-based document/form instead of a GH issue?

> Questions and a free form communication should happen in the first type of issue

This should happen in the proposed gdoc/form (or alternatively, in the "guided" GH issue where free-form communication may happen).

> One template is meant as before

I like that!

> to be a form for the community representative to fill.

I don't like that! 😉 

> ,and the community rep only fills in the new hub form when they have all the info they need.

IMHO, the translation should happen on our side!!
I mean, when all the needed information is available in the gdoc/form (or the "gathering info" GH issue), WE (me, @jmunroe @colliand) create the new hub request.

@2i2c-org/tech-team, immediate thoughts? cc @jmunroe @colliand 

I know having a new gdoc/form might be more than a simple step forward, so I would be OK to keep things decouple in different GH issues as @GeorgianaElena is proposing as a first iteration.

**Comment by damianavila** [comment]
> I know having a new gdoc/form might be more than a simple step forward, so I would be OK to keep things decoupled in different GH issues as @GeorgianaElena is proposing as a first iteration.

Yeah... that is probably the proper +1 iteration.

**Comment by damianavila** [comment]
> I actually have an idea about how to put these all together (in this iteration or the next?). How about:

I like that idea! Because we are effectively splitting the process (and the new hub issue structure) and we have the ability to optionally introduce the gdoc/form for the first part of the process if we wish to take that step (and I think we should).

**Comment by choldgraf** [comment]
I think the general approach that @GeorgianaElena describes sounds good to me. This is similar to the oldest iteration of this process, where we used this google form to ask questions about the use-case:

- [link to "help us understand your use case"](https://docs.google.com/forms/u/1/d/1KHw-4Wdyoofv-6CENeiOSbnC62LKdx55QTcZmXQVkkc/edit?usp=drive_web)

We could either re-purpose that or build something from scratch w/ that as inspiration?

If I recall, the reason we moved _away_ from a google form was because it added another thing to keep tack of, a new kind of information (PDF) to store somewhere, and this added complexity to the process. If we want to move back to a Google Form setup, we should make sure that this interfaces with the work @jmunroe is doing around refining our leads and active contracts process so we know where to put information:

- https://github.com/2i2c-org/team-compass/issues/325

**Comment by GeorgianaElena** [comment]
> If I recall, the reason we moved away from a google form was because it added another thing to keep tack of, a new kind of information (PDF) to store somewhere, and this added complexity to the process.

Absolutely! I still think that this shouldn't add another thing to track for someone on the tech team, but rather be something that helps the members of the 2i2c team that are responsible for getting this info out of the communities.

So yes, it probably makes sense for @jmunroe and others on the leads team to agree or propose a process that works for them before moving forward?

From my perspective as someone on the tech team, what I *think* would improve the deployment workflow would be having:

- a space to be pinged whenever needed, esp when hubs have special, maybe new requirements, but without being the one responsible for moving the lead forward in its process.

- a space where all initial info for deploying a hub is curated and be responsible for making it happen

- tasks to improve an existing hub deployment based on feedback from communities (possibly coming through support)

> We could either re-purpose that or build something from scratch w/ that as inspiration?

I wouldn't like to block this first iteration on having the perfect form. But rather transfer the current info that we have into a form that's more comfortable for communities and leads team and create the 2 spaces that I mentioned above.
What do you think?

**Comment by damianavila** [comment]
> I wouldn't like to block this first iteration on having the perfect form. But rather transfer the current info that we have into a form that's more comfortable for communities and leads team and create the 2 spaces that I mentioned above.

+100 on that idea!
I think we should focus this first step on making life easier for the engs whereas at the same time we leave the place open to push forward with a different model (introducing a google form or any other platform).
Even when I would love to have @jmunroe feedback on how we properly get info from the community representatives, this issue should be focused on setting up a base system with the 2 spaces @GeorgianaElena is talking about. Once we have that one ready (as per @GeorgianaElena's proposal in the PR), we can go deeper into how we evolved each of those.

**Comment by jmunroe** [comment]
I agree with splitting up the process into two steps. The actually translation into an issue to provision the hub should be made by someone internal to 2i2c for consumption by 2i2c engineering. I'll add this comment to PR#1733 but it should have some reference to contract negotiation/quote that is related to this hub request.

I am not as clear on the role in the community rep in specifying the requirements of the hub. We are not at the level of "self-service" where it makes sense for a community rep to make specific technical requests. These need to part of overall partnership agreement and so I think necessarily need to involve someone from @2i2c-org/partnerships-and-community-guidance working with the community rep to collect the needed data. 

I agree that we need to collect this information from the community rep somewhere that is visible (so not via email) but it is not obvious to me to use GitHub issues or a Google Form or something else. I can see pros and cons for each of those tools.
