### ISSUE TITLE
Extract-replicate our AWS cluster creation workflow into the mybinder.org-deploy repo

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1824]
Ref: https://github.com/2i2c-org/infrastructure/issues/919

Upstream issue where the discussion is going to happen: https://github.com/jupyterhub/team-compass/issues/501.

@sgibson91, feel free to add any further details on this one.

**Comment by sgibson91** [comment]
The repo already has a workflow for deploying Binder - we need to extract our workflow for creating a cluster in AWS, i.e., eksctl and terraform.

**Comment by damianavila** [comment]
> we need to extract our workflow for creating a cluster in AWS, i.e., eksctl and terraform.

@sgibson91, it is not clear to me if you intend to work on this one in this sprint or if you were just talking about referencing the upstream issue and having the discussion over there. Let me know what you think and I will update the sprint board accordingly. Thanks!

**Comment by sgibson91** [comment]
I can't really work on this one until #1823 is done, so maybe for the next sprint

**Comment by damianavila** [comment]
@yuvipanda will reply with more context on this one.

**Comment by yuvipanda** [comment]
The *primary* reason we use eksctl is:

1. EKS managed nodegroups (similar to GCP nodepools) *can not* scale to 0: https://github.com/aws/containers-roadmap/issues/724
2. Managed Nodegroups are available via terraform (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group) but *unmanaged* nodegroups are only available via a flaky terraform module that is fucking around with autoscaling groups, etc
3. Since we provision many different notebook nodegroups and many different dask ones, it will *cost* a lot of money if we need to have at least 1 of them all the time up!
4. However, for mybinder.org we'll only have *one* nodegroup, and it's ok if it scales down to 1 not 0. I think it's fine to just use the available `eks_node_group` resource for mybinder

**Comment by sgibson91** [comment]
Thanks Yuvi! I will ping you for review on the appropriate terraform config to extract :)

**Comment by yuvipanda** [comment]
@sgibson91 yay great! With a *super quick* look, I think there is not much (perhaps the CI/CD stuff) as most of the rest (scratch buckets, EFS, etc) aren't going to be needed on mybinder.org. I'd suggest looking at starting from scratch as a possibility too. Happy to help in whatever form!

**Comment by yuvipanda** [comment]
I provided more info in https://github.com/jupyterhub/mybinder.org-deploy/issues/2449#issuecomment-1329980627.

**Comment by damianavila** [comment]
Do not use AWS ECR.
AWS cluster autoscaler behaving weird.

**Comment by damianavila** [comment]
Erik and Sarah made progress. We need to define the next steps.

**Comment by sgibson91** [comment]
Yuvi helpfully reviewed the [upstream PR](https://github.com/jupyterhub/mybinder.org-deploy/pull/2467) for AWS-terraform config and merged it. I think others in the mybinder community will be pushing forward other pieces of technical work (such as actually deploying the BinderHub) as we increasingly see a need for an AWS-based federation member, and there looks to be a couple of other folk who wish to contribute AWS credits.

I'm closing this one.
