### ISSUE TITLE
Enable GitHub authentication to our Grafana dashboards for all *dedicated* clusters

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1827]
We should allow the Comm Reps/Hub Admins of any hub on a **dedicated** cluster to access the Grafana dashboards depicting monitoring info for their infrastructure.

**List of dedicated clusters:**

(I don't know which, if any, already have this feature enabled so please feel free to tick off those you know about)

- [ ] awi-ciroh
- [ ] callysto
- [ ] carbonplan
- [x] leap
- [x] m2lines
   - #1803 
- [ ] meom-ige
- [ ] nasa-cryo
- [ ] openscapes
- [ ] pangeo-hubs
- [ ] utoronto
- [ ] uwhackweeks
   - https://github.com/2i2c-org/infrastructure/issues/1570

**Comment by consideRatio** [comment]
> We should allow the Comm Reps/Hub Admins of any hub on a dedicated cluster to access the Grafana dashboards depicting monitoring info for their infrastructure.

We don't provide access, but, we meet the title description of enabling github authentication.

https://github.com/2i2c-org/infrastructure/issues/2175

I'll go for a close here suggesting that:

1. We add any github team who needs access by a simple update to the support chart config if a hub representative requests this.
2. We consider providing access based on a `prod` hub's jupyterhub as an identity provider so that they are granted access by default no matter on how they have configured login.

**Comment by consideRatio** [comment]
Alternatively, we could also send out emails to all hub representatives. I can open an issue with this idea if wanted - just ping me and I'll create an issue towards that.
