### ISSUE TITLE
Q4 2022 Goal: Billing

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1853]
### Context

We acknowledge the fact we need to effectively bill our communities to be sustainable in the long term.

And there are some aspects of the billing process where Engineering can help with getting the usage data, aggregating that information, and automating the delivery.

We have different sorts of deployments (ie. dedicated vs shared) where usage computation is different and we should account for and develop stuff taking into consideration those differences.

### Proposal

* [ ] #1921
* [ ] #1922
* [ ] #1923

### Updates and actions

Created child issues to work on that will be further specified by @yuvipanda.

**Comment by consideRatio** [comment]
## Related issues
- https://github.com/2i2c-org/infrastructure/issues/1575
- https://github.com/2i2c-org/infrastructure/issues/1921

**Comment by choldgraf** [comment]
### Question: What's the status of our cloud cost recovery?

I know that last year, @jmunroe undertook a big effort to define the cloud costs for each of our communities and send invoices to them via CS&S. What has happened since then? Note that [we now track our cloud cost summary stastics in the KPIs page](https://2i2c.org/kpis/finances/#cloud-costs-recovery). So that indicates we're spending between $4-8k a month on cloud (which is almost a full FTE!)

Here are some specific questions / to-dos we should make sure to tackle:

- Have we sent cloud cost invoices for December and January? If not, can we do so?
- Can we document the process we currently follow for tracking cloud costs, even if it is manual?
- Can we give CS&S recommendations for what they should adjust to help us in this process? (https://github.com/2i2c-org/team-compass/issues/663)

**Comment by damianavila** [comment]
> Have we sent cloud cost invoices for December and January? If not, can we do so?

@jmunroe should have that answer, I don't know.

> Can we document the process we currently follow for tracking cloud costs, even if it is manual?

@jmunroe, did you take notes of the manual process the last time you did it?

> Can we give CS&S recommendations for what they should adjust to help us in this process? (https://github.com/2i2c-org/team-compass/issues/663)

+1

> Who is responsible for this effort? Is it engineering? Or community/partnerships? I think we need somebody to spearhead leading this effort to make sure we don't drop it.

IMHO, the leading actor in the billing process "as a whole" should be the Community/Partnership side because they have a more direct interaction with our communities and CS&S. This issue tried to capture some of the Eng-related pieces (and aspects) of that whole billing process.

**Comment by damianavila** [comment]
During Q4 there was some progress at https://github.com/2i2c-org/infrastructure/issues/1921.
During Q1, I expect that one finally land in our infrastructure.
The remaining items (child issues) should be addressed in the next billing theme iteration (realistically, proto-Q2 content).

I am closing this one now (as Q4 has long ended) but I know there is an ongoing discussion above, so feel free to keep commenting on this issue in you are inclined to.
