### ISSUE TITLE
Move VICTOR's hub image to use a Dockerfile

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1934]
### Context

ref: https://2i2c.freshdesk.com/a/tickets/288

In this ticket, a specific version of `gdal` is required in the image but wouldn't correctly install. We eventually tracked this down to the fact that the base image used by repo2docker is Ubuntu 18.04 (bionic). Information was requested on how an install of Ubuntu 22.04 or a newer version of apt could be achieved. I don't think this is possible without reconfiguring the repo to use a Dockerfile - which is perhaps work we should do ourselves, rather than leave to the community.

Image repo: https://github.com/volcanocyber/VICTOR-notebook

**Comment by yuvipanda** [comment]
Replicating my message in freshdesk:

Hi Samuel,

In general, it is always good to get packages from conda - even if you got gdal from apt, packages that are coming from conda that *depend* on gdal will still use the gdal from conda! So this usually causes confusion with respect to versioning.

So I dug into *why* the conda version was only pulling in an older version of gdal. The error message Sarah pulled out indicated that when gdal newer version is specified, conda just tries to find compatible versions and fails. I dug a little deeper, and discovered this is because the *default* version of python used is 3.7, and that is the last version of gdal that can be resolved with that!

So https://github.com/volcanocyber/VICTOR-notebook/pull/1 bumps up the version of python to 3.10, and that brings us a newer gdal :)

I've also opened https://github.com/2i2c-org/hub-user-image-template/pull/20 to set 3.10 as the new default in our template so others don't run into this problem. I'll also be opening an issue in repo2docker soon to bump the default there as well.

Try merging that PR and testing it out? Hope that helps!

Thank you :)

- Yuvi

**Comment by yuvipanda** [comment]
I have now opened https://github.com/jupyterhub/repo2docker/pull/1219 as well upstream to bump up the default python to 3.10. In addition, there is https://github.com/jupyterhub/repo2docker/pull/909 that would allow us to move away from 18.04 - but I think that should be orthogonal to the issue here.

**Comment by yuvipanda** [comment]
We have solved this without them needing to use a dockerfile.
