### ISSUE TITLE
Migrate the VICTOR hub to use GitHub Teams-based auth

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#2043]
### Context

The VICTOR hub would like to migrate to using GitHub Teams for auth in order to more easily manage their users.

ref: https://2i2c.freshdesk.com/a/tickets/318

**What needs to be done?**

- [ ] Confirm what teams to grant access to
  - There has been discussions about specific permissions to specific users based on team membership, such as GPU access or not. For now list all teams of relevance and let us focus on such permissions as dedicated matter after we have migrated to GitHub authentication.
- [ ] Confirm what to do with existing user storage, options are:
  - [ ] backup and start fresh - backups will be accessible only with manual help by 2i2c going onwards, 
  - [ ] delete and start fresh
  - [ ] migrate users storage
    - [ ] We need a table of existing user names and their respectivegithub handle
- [ ] Migrate the auth ([related documentation](https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/configure-auth/github-orgs.html))

### Updates and actions

- Erik: I've asked Samuel to respond to this issue and provide relevant information.

**Comment by volcanocyber** [comment]
Hi all,

This is the team I would like to add users to in order to give them access to the hub: https://github.com/orgs/VICTOR-Community/teams/victoraccess. As we figure out the exact data science tools and methods we are using, GPU access will be nice, but I agree that it is not as important right now.  I would prefer to migrate users storage, and as far as i know, the user names and their github handles are the same. Otherwise, feel free to backup and start fresh. There are only a handful of people actively using the hub currently, and I have warned them about the change. Let me know if theres any other information you need,

**Comment by consideRatio** [comment]
I'm referring a question from [a support ticket](https://2i2c.freshdesk.com/a/tickets/370) to this issue:

> I'm just wondering if you have a general timeframe as to how long this process will take. I was planning on adding about a dozen new users in the coming days, but I want to hold off to make the migration of home directories easier.

I can't provide you with a timeframe, but @sgibson91 is assigned to get this done.

**Comment by consideRatio** [comment]
@sgibson91 @volcanocyber I understand now that user storage is trivial to migrate, because this is not a change from some other identity provider to github as an identity provider, its just a change on what users are declared as authorized to have access and not.

So, active user storage migration is not needed - everything will just work without active intervention.

**Comment by sgibson91** [comment]
@volcanocyber can you (_temporarily_, I'll remove myself once I'm done) make me an owner of the of the `VICTOR-community` org so that I can properly setup the OAuth app please?

**Comment by sgibson91** [comment]
@volcanocyber once #2060 is merged, the migration will be complete!

When you log in again, you will most likely be asked to grant access to the GitHub Oauth App again. Make sure to click "Grant" for the `VICTOR-Community` organisation (or whichever button is next to it) **BEFORE** clicking "Authorise 2i2c-org" at the bottom. Then auth by Teams should work. See screenshot below for context (I'm demo'ing the`binderhub-test-org` org in it)

![Image](https://user-images.githubusercontent.com/44771837/213421800-1f943a78-cd81-42e1-afbd-ee174f3c30c9.jpg)
