### ISSUE TITLE
How is the CILogon experiment going?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#2076]
Hey @2i2c-org/engineering team - I got this e-mail from the CILogon group today:

> It's been a while since we talked, so I want to check in and see how things are going. Has CILogon been working well for 2i2c? Do you have feedback for us? Should we schedule a call to sync up and discuss future plans?

Can I get feedback from folks on how this pilot is going? Do we like CILogon? Do we plan to keep using it / grow our usage? If they ask us to start paying for a license, do we accept? If so how much do you think it's worth?

I think we should try to get back to them quickly, and if it seems like we need to have some ongoing discussions then somebody on the @2i2c-org/engineering team should take point so that I am not a bottleneck.

**Comment by choldgraf** [comment]
cc @GeorgianaElena and @yuvipanda who I think have specifically worked on this

**Comment by consideRatio** [comment]
From my perspective of setting things up based on docs using `deployer` automation, this has been working out great!

**Comment by yuvipanda** [comment]
It has been working amazing! @GeorgianaElena is our local expert i think

**Comment by choldgraf** [comment]
OK, I will respond to the e-mail telling them that it's going really well and we hope to keep using it. I think they'll ask for compensation soon and in my opinion that is something we should start paying them unless it is astronomical. I'll plan to interface with them via e-mail w/ this plan unless I hear otherwise from folks. I'm also going to loop in @damianavila to the e-mail so that I'm not the only contact.

**Comment by GeorgianaElena** [comment]
> Can I get feedback from folks on how this pilot is going? Do we like CILogon?

I am also happy with the current CILogon setup at 2i2c. 
They were very responsive when we needed help (for example https://2i2c.freshdesk.com/a/tickets/293).
Also, I feel like the 2i2c CILogon integration also sparked some improvements in the upstream `jupyterhub/oauthenticator` project.

> Do we plan to keep using it / grow our usage?

Yes

> If they ask us to start paying for a license, do we accept? If so how much do you think it's worth?

I believe we should accept. 

### Blog post
I believe in the beginning we were planning also to write a blog post abut this. The idea of of writing a blog post about all the great stuff that had happened since we've got the free  subscription from them as a token of appreciation, came up again more recently, but unfortunately we didn't manage to prioritize it I believe (https://github.com/2i2c-org/meta/issues/381#issue-1373006206 for example). But I still believe it's a good idea and I would be very happy to help out with that if folks think is a good idea.

**Comment by choldgraf** [comment]
@GeorgianaElena I'm all for a blog post - I mentioned it to them again in the e-mail to CILogon, so I think they'll be happy about it.

I suggest that we write a quick blog post to highlight how the integration works and generally celebrate the partnership. Don't set the bar too high @GeorgianaElena - an imperfect blog post is better than no blog post :-)  I am happy to provide editing and guidance on wording/structure if need be.

**Comment by GeorgianaElena** [comment]
> an imperfect blog post is better than no blog post :-) 

Yes, agree!

> I suggest that we write a quick blog post to highlight how the integration works and generally celebrate the partnership.
 
I believe this needs a dedicated issue, otherwise we risk to de-prioritize it again. I think I'll open one in https://github.com/2i2c-org/2i2c-org.github.io

**Comment by GeorgianaElena** [comment]
Actually, I just noticed we have an issue template in team-compass for blog posts ❤️ https://github.com/2i2c-org/team-compass/issues/new?assignees=&labels=%3Alabel%3A+blog-post&template=blog-post.md&title=%5Bblog%5D+POST+WORKING+TITLE

**Comment by GeorgianaElena** [comment]
I've opened https://github.com/2i2c-org/team-compass/issues/621 to track the blog post. I believe we can now close this issue?

**Comment by choldgraf** [comment]
Yep - happy to close the issue as I think I have my answer: CILogon is going great!
