### ISSUE TITLE
Plan for support process during team retreat, jupytercon & reduced availability after

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2438]
I think a lot of us would be flying, at the retreat, at jupytercon and on vacation in mid May. We should have an explicit plan for figuring out what kind of support will be available, and who will be doing it during this time.

**Comment by damianavila** [comment]
The first part of the plan for the retreat and JupyterCon: this will be a wide and general reduced availability phase for the team and because of that we should treat it such as an EOY period as stated in our docs:
* https://team-compass.2i2c.org/en/latest/people/time-off.html#expected-end-of-year-time-off
and follow the process outlined in:
* https://team-compass.2i2c.org/en/latest/projects/managed-hubs/support.html#support-process-during-expected-time-off

We should figure out who is going to provide that minimal support during that whole week and we have a few alternatives:
1. We just follow the calendar rotation.
2. We make the whole eng team part of the "incident resolution team" so we spread the load among team members.
3. Something else?

@2i2c-org/engineering and @jmunroe thoughts are welcome on this matter.

For the reduced capacity after those events (several team members taking vacation time during that time window), I think we just need to follow the calendar rotation and find alternative team members if your away time overlaps with the planned support rotation (not different from any other times). Btw, currently, I do not see substantial overlapping but each team member should re-check because we recently changed the support role cadence to 14 days and that might impact your previous calculations (I could review each request and point out the overlapping for each team member but if you all can do it by yourself that would be of great help for me, thanks!).

**Comment by consideRatio** [comment]
I can do stewarding during the team retreat Tuesday (May 9) and onwards, but I have the week before scheduled for pure vacation time in https://github.com/2i2c-org/meta/issues/442 (the rotation changed after I opened that Away issue).

![image](https://user-images.githubusercontent.com/3837114/230945364-b6f5618a-cfd3-4cc9-94a8-f055662e62df.png)

Maybe someone can cover for my vacation time?

**Comment by damianavila** [comment]
OK, I have a plan and next steps!

As I said before, we recognize the upcoming period as an "expected time off and downtime" period and we follow, in general, the process outlined at https://compass.2i2c.org/projects/managed-hubs/support/#expected-time-off-and-downtime, with the following specifics:

1. @GeorgianaElena has agreed to be our "triage steward" during the 2i2c retreat and JupyterCon since she is already in the support rotation during this period. Thanks, Georgiana!!!
2. The support operations during this time are essentially covered by this policy: https://compass.2i2c.org/projects/managed-hubs/support/#expected-time-off-support-policy.
3. If there is an incident the whole @2i2c-org/engineering team will be supporting Georgiana (who will be effectively serving as the incident commander) so we can ALL minimize the time we spend on the incident.

Action items:
* [ ] We need to update our FD footers as indicated in https://compass.2i2c.org/projects/managed-hubs/support/#support-process-during-expected-time-off.

**Comment by damianavila** [comment]
Additionally, @GeorgianaElena is AWAY on May 15th and 16th (and beyond), so I proposed Erik's May 8th and 9th rotation time to be switched with Georgiana's rotation time so we effectively have coverage during May 15th and 16th since Georgiana is already covering 8th and 9th as the "triage steward". @consideRatio can you please confirm if you do support on May 15 and 16th? Thanks!!

**Comment by consideRatio** [comment]
I can be support steward monday/tuesday may 8-9! I recall having planned for that but may have failed to add updates about it :/

As long as im free until may 8 everything works for me!

**Comment by consideRatio** [comment]
Oh, i can be May 15 and 16 also.

Im on a mobile and cant lookup status of schedule etc, but overall i can support steward whenever its needed may 8 and later.

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena has agreed to be our "triage steward" during the 2i2c retreat and JupyterCon since she is already in the support rotation during this period. Thanks, Georgiana!!!

Yes, I agree to be covering the usual support shift during the week in Paris, operating on a reduced support capacity. 👍🏼 

However, I still believe I shouldn't be doing it alone and still have a team of two people doing support most of the time.

- @consideRatio should be my buddy during the first two days, May 8 and May 9. But as @damianavila mentioned, on the May 15 and May 16 both me and @jmunroe will be on time off, which means there won't be anybody covering support, hence @damianavila 's proposal for me to serve alone on the May 8 and May 9 and have Erik cover for 15 and 16 May.

    > Oh, i can be May 15 and 16 also.

  @consideRatio, I really appreciate this and I will take this offer if you still want to both be my buddy on May 8 and 9 and cover for me on May 15 and 16. I can cover for you for two days during your next rotation in exchange if you'd like.
- [ ] @consideRatio, can you let me know if this ⬆️  is something you can and wish to do? Thank you.

- @jmunroe should be my buddy during the last three days of that week, May 10, 11, 12. 

- [ ] @jmunroe can you please let me know if we agree to be my support buddy during these days of the JupyterCon
 I was my understanding from talking with @damianavila that there is a plan to have you removed from the rotation but I'm not sure when this should be in effect?
 
 > The support operations during this time are essentially covered by this policy: https://compass.2i2c.org/projects/managed-hubs/support/#expected-time-off-support-policy.
 
I want to recognize and signal the last part of that document https://compass.2i2c.org/projects/managed-hubs/support/#rotating-team-members-during-expected-time-off which refers to rotating members during these reduced time periods, that we do not keep track of it in any way yet.
Chance got me again  on rotation during an expected downtime support period 😅 , which I don't mind, like I said. But I would like us to start keeping track of this so we can make the necessary adjustments in time next time it happens.

**Comment by consideRatio** [comment]
@GeorgianaElena i'll support with you on both pairs of dates!

**Comment by damianavila** [comment]
> I was my understanding from talking with @damianavila that there is a plan to have you removed from the rotation but I'm not sure when this should be in effect?

@GeorgianaElena, a little clarification, this is not yet a plan 😉, I was giving my impressions about the fact I feel @jmunroe, in the future, should be out of the current eng-y focused rotation because he actually needs to deal with community-facing support tickets on a frequent basis.

**Comment by damianavila** [comment]
Discussion about the length of the "expected time off and downtime" period: https://github.com/2i2c-org/team-compass/issues/735#issuecomment-1533813978.

**Comment by jmunroe** [comment]
+1 on removing @jmunroe from the current eng-y focused rotation. It's been really helpful (learning) to see the requests from communities come in and how the triage/support process works in practical terms. But the reality is any actual 'L2 support' level request that involves touching the infrastructure is not something I do in my currect role which makes me a poor match for the rotation.

Support requests at that not L2 should continue to tagged to community/partnerships. I think a goal could be that most of those questions should have answers in our public facing documentation, and if they don't, that's a signal to community/partnerships to create that documentation.

**Comment by yuvipanda** [comment]
Are there action items we should take from this before closing?
