### ISSUE TITLE
Transition clusters providing users with dedicated nodes to use shared nodes

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2661]
## Brief description

Many jupyterhub's setup by 2i2c were initially setup to start dedicated nodes for users, this has several drawbacks that we can avoid by scheduling multiple users to run on individual nodes.

### Drawbacks of dedicated nodes

- inefficient use of cpu/memory paid for
  - increases cost
  - increases required cloud quota to request to scale to support X users
- increased average startup times (server startup, image download)

## Rationale & value to our mission

- expected reduced cloud cost for communities
- faster startup times on average
- it becomes easier to handle events

## Definition of completion and success

All communities use node sharing, even if options aren't presented like in many educational hubs.

## Action points

- [ ] Overview all communities still setup to provide user dedicated nodes
- [ ] Help them transition

## Related

- #3256
- #3030

**Comment by yuvipanda** [comment]
Thanks for writing this up, @consideRatio. I would love some help in helping me evaluate this goal - I don't fully understand *why* the current CPU and memory limits are set the way they are, especially that the description does not match the actual values set for CPU limits (for example, see https://github.com/2i2c-org/infrastructure/blob/5c57c9d6e263f1ecc88b0d29625faa9751165b73/config/clusters/leap/common.values.yaml#L158). It doesn't quite match the mental model I have for how limits work. Have you written up about this somewhere? I'd love to read more, because I don't understand how this currently works at all.

**Comment by consideRatio** [comment]
@yuvipanda yes sorry about not communicating clearer about this, its very relevant that that the current state is better documented, and also evaluated and refined!

I'd really love to sync up about this in a chat focused on the topic of requests/limits. If we could have that before I start to write about current state, it would be really helpful for me! Maybe we can find time next week?
