### ISSUE TITLE
Move 2i2c cluster's prometheus data from slow spinning disk to fast SSD

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3111]
The 2i2c shared cluster's prometheus data is on the slowest possible pd-standard disk. We should move this to a pd-ssd with minimal data loss.

**Comment by yuvipanda** [comment]
I JUST DID THIS AND OMFG EVERYTHING IS SO MUCH FASTER WTF

**Comment by consideRatio** [comment]
Nice!!! :D

**Comment by jmunroe** [comment]
That's great news.

Given that these Prometheus databases is a critical part of our infrastructure (especially for the shared cluster since they are used in for our billing), what's the backup strategy for these pd-balanced disks?  Is the data replicated elsewhere or backed-up outside of each cluster?

**Comment by yuvipanda** [comment]
@jmunroe there isn't one! Can you open an issue so we don't lose track of it here? Thanks!
