### ISSUE TITLE
Update 2i2c splash image on research-delight hub login page

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3127]
### Context

The splash image for the research-delight hub located at https://researchdelight.2i2c.cloud is out of date.

![image](https://github.com/2i2c-org/infrastructure/assets/1879041/43231f6f-03a4-4fbd-b782-878ee106af35)

### Proposal

The out-of-date splash image should be replaced with the new 2i2c brand, perhaps this image:

![image](https://github.com/2i2c-org/infrastructure/assets/1879041/d26f9ecf-3f1c-419a-ab79-8aaf20b83a05)

I'd like this image to be closed by @colliand or @jmunroe following best practices guidance for `how to customized the hub login page` from 2i2c's engineering team. Thanks in advance to @damianavila for advice. 

### Updates and actions

- [x] Identify code base or repo that controls the research-delight splash image
- [ ] where will new brand assets be robustly stored?

**Comment by colliand** [comment]
Yay! I found the docs: https://github.com/2i2c-org/default-hub-homepage

**Comment by yuvipanda** [comment]
It's probably coming from https://github.com/2i2c-org/infrastructure/blob/a5fa81b72792c1bb8c14647dd1e65d507c2d0438/config/clusters/2i2c-aws-us/researchdelight.values.yaml#L20

**Comment by colliand** [comment]
And more docs so that Jim learns how to do this... https://infrastructure.2i2c.org/howto/features/login-page/

**Comment by GeorgianaElena** [comment]
@colliand and @jmunroe, I've opened https://github.com/2i2c-org/2i2c-org.github.io/pull/181 to update the logo shown at https://2i2c.org/media/logo.png directly, instead of updating the link.

This is because there are other hubs that use the 2i2c splash image, not just the research-delight one that would benefit of this update this way. 
Hope this is ok.

**Comment by colliand** [comment]
Thanks @GeorgianaElena!

**Comment by jmunroe** [comment]
Thanks @GeorgianaElena for resolving the particular task. 

I think @colliand was also trying to use this as excuse to understand the broader process of managing and changing a hub landing page so that he and I have more practical knowledge on how to advise community reps on best practices for their communities. And to learn how we can improve the service for our communities. 

With respect to the Research Delight hub, the intent here is to view 'James and Jim' as the community reps for this community and have us work through the process for managing this hub _like any other community_ would have to do. 

So for this particular request (updating a splash image in the default hub landing page), the current process does require a PR to our infrastructure repo.  There are four pathways I can see such a request coming in:

1. A PR to the infrastructure repo itself.  A community rep could make this PR themselves to by changing the URL (as suggested by Yuvi). The advantage here is that the community rep has taken part in the shared responsibility/right to participate in maintenance of their hub.

https://github.com/2i2c-org/infrastructure/blob/a5fa81b72792c1bb8c14647dd1e65d507c2d0438/config/clusters/2i2c-aws-us/researchdelight.values.yaml#L20

2. A support ticket to support@2i2c.org to request that this update be made. Since it is relatively quick, I would assume that the support steward would make this change without necessarily creating a corresponding GitHub issue.

3. A GitHub issue in this repo requesting that this change be made. This is effectively the way that this particular issue was handled in practice.  But I'd like to note that I am hesitant to recommend to communities to directly create issues in our infrastructure for items that are really support requests. While for any one issue, it is not a big deal but as 'support requests' generally I like to be able to consistently log and track how we resolve them.

4. Asking someone on the 2i2c team (by email, slack, or in person) to make this change on their behalf.  In this case, my recommendation is that a 'New Support' ticket in Freshdesk be created on the community's behalf so that the request is handled in a queue with other concurrently received support requests.

One pathway which does not appear to be a current option is having some sort of UI within JupyterHub itself (as an extension to the configurator) that would allow community reps make these change of landing page logo on their own with no engineering involvement at all. This feature might even involve a 'upload your logo/drag-and-drop' front end or something.  This is of course out of scope for this short request but it is a list of these kind of product development tasks I think we are trying to identify.

Relatedly, while there is some internal engineering documentation on [configuring the landing page](https://infrastructure.2i2c.org/howto/features/login-page/), there is not a corresponding page in our [Service Guide](https://docs.2i2c.org/). Also, there is no mention that community partners that they are not constrained to using the default hub landing page template but can also replace it a completely custom landing page (example: https://hub.ghg.center/)


[I'll copy paste this last comment to a new issue in meta/ to continue the discussion.  I just wanted to get some thoughts down while I was thinking about them]

**Comment by colliand** [comment]
Thanks @jmunroe! You appear to be reading my mind. Yes, let's continue the "how to enable community's update login pages?" discussion in meta. 

I am super grateful for the elegant way that Georgiana resolved this issue and simultaneously addressed other placements of the old logo.
