### ISSUE TITLE
write access to an S3 bucket - with limits

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#3157]
### Context

Hi @yuvipanda,

We're wondering if it's possible to set up write access to an S3 bucket, with configuration so individuals don't need to use credentials. We've had this request from researchers experimenting in the hub, and believe you've done something similar with CryoCloud. 

Our only concern is that we have to enforce the "no egress" and have some cloud alerts to monitor costs. Would this be possible and would you have insights on how to have alerts/thresholds? We would expect this to be <$100 per month. Happy to discuss further, and thank you! cc @betolink

**Comment by betolink** [comment]
The use case for this is to enable more "cloud native" workflows, when using Dask it's easier and faster to write to S3 than the local EFS volumes. I noticed that the Cryocloud buckets are cleaned after their workshops, we could do the same. 

I have no idea if at the end of the month AWS charges by the average data stored or what. Say we run a workshop and collectively put 500GB of data and deleted it after a day or 2. This will be for explorations not for production that's why we would like a policy with

* no egress allowed out of us-west-2
* 1TB max capacity 

What do you think @yuvipanda ?

**Comment by yuvipanda** [comment]
yeah, what we do in general is to have a 'scratch bucket'. It has the following features:

1. Is in the same region as your hub
2. Can actually only be accessed from *within your hub* and nobody else. 
3. Everything here gets deleted after 7 days of being created. There's no way to restrict size, but this in practice has worked out well.

Auth is automatically set up, users don't have to do anything on the hub. The name of bucket is available via an env variable.

We don't really have an automated way of alerting for costs yet, but I think on openscapes you should be able to look at and monitor this yourselves. The automated deletion usually keeps things down.

How does that sound?

**Comment by jules32** [comment]
This sounds awesome, and super helpful for users. Thank you!

**Comment by yuvipanda** [comment]
@jules32 I've set this up in https://github.com/2i2c-org/infrastructure/pull/3190, and temporarily deployed it to the staging hub.

You will see the existence of an env var named $SCRATCH_BUCKET that you can use. This will be different for each hub, so what is in staging and prod will be different. It'll also actually have a reference to the *username* as well, so each user can treat it as their own personal space. This is so that multiple people can share a notebook with a reference to $SCRATCH_BUCKET and not overwrite each others's data! However, there's no access control here - anyone can read from or write to another person's 'space' in the same bucket.

Everything will be deleted 7 days after creation to keep costs down as well. Users don't need to do anything with auth :)

I tested this by opening a terminal, then doing:

```bash
pip install awscli
aws s3 ls $SCRATCH_BUCKET
```

This should get deployed to prod once that PR is merged, but lmk if this pattern works for you.

**Comment by jules32** [comment]
This is super @yuvipanda , thank you! We will share with folks for testing; I believe this pattern will work for them :)

**Comment by yuvipanda** [comment]
@jules32 fully setup now!

**Comment by jules32** [comment]
thank you!
