### ISSUE TITLE
[Support question] How to securely make available a token to hub users

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3325]
In https://2i2c.freshdesk.com/a/tickets/1042 there is a question on how to inject a secret token into a user image.

However, this is not something recommended from a security standpoint. 

What would the step forward be in this case? cc @2i2c-org/engineering

**Comment by consideRatio** [comment]
The secret shouldn't go into the image itself in any way, because then it needs to be protected at all cost.  If the image itself is sensitive, we would then need to have credentials to pull the image - so another secret is introduced for us to manage anyhow. So a big :+1: to making sure they don't put it in the image itself. I think it must be added to the pod/container we start for users - which is above their control.

It could be declared directly with `jupyterhub.singleuser.extraEnv`, or indirectly with `jupyterhub.singleuser.extraEnv` referencing a k8s Secret. Examples are available in the [z2jh configuration reference]. The benefit of doing the indirect approach is that anyone with "kubectl get pod" permissions can't reveal the sensitive information, but requires "kubectl get secret" permissions.

`jupyterhub.singleuser.extraFiles` is perhaps also plausible to use, then the credentials would be mounted to the container as a file through a k8s Secret managed by the z2jh chart.

When `gh-scoped-creds` is configured, there is no sensitive information involved, so I think this is the first time we need to think about this. I think this could merit some careful thoughts involving all @2i2c-org/engineering. How should we let users get sensitive credentials to their servers, credentials that ideally isn't given to us either?

Ideally, they would from their servers visit some external site to acquire temporary DB credentials, that would be similar to the `gh-scoped-creds` situation. But, there are no temporary DB credentials - just a fixed password, so what to do?

- Should we manage the credentials in 2i2c-org/infrastructure as a SOPS encrypted secrets - in practice putting it in Google's KMS system?
- Should we manually create a k8s Secret once in the cluster (which then can't be re-deployed to another namespace etc, because we have manually created a resource), and mount it via `singleuser.extraEnv`?
- Should we search for another way for them to fetch credentials from their user image, similar to how `gh-scoped-creds` work, but for example against their owns KMS system?

I'm not sure how we ought to handle this need long term or short term, but the quickest strategy is to add a encrypted values file declaring `singleuser.extraEnv` with a key/value directly. Drawbacks: `kubectl get pod` is enough in the k8s cluster to read it and we end up managing communitys sensitive credentials.

**Comment by yuvipanda** [comment]
> add a encrypted values file declaring singleuser.extraEnv with a key/value directly.

This is what I recommend we do.

**Comment by GeorgianaElena** [comment]
Thank you very much for all of your quick your input <3! I've followed up on the ticket with this info, so I will close this issue and open a new one if they wish to go forward with this, so we can update their config.
