### ISSUE TITLE
Do a manual run of billing for cloud costs for dedicated clusters on AWS for Jan-Mar 2024

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3725]
### Context

We want to have clear and detailed documentation for how various billing processes can be done *manually* by someone other than me. This helps remove me as a bottleneck / single point of failure, and paves the way for fuller automation.

This issue is focused simply on AWS and dedicated clusters. There will be another issue for doing the same on GCP.

### Proposal

- [x] Yuvi writes documentation (a runbook) for manually reporting AWS cloud costs. No process improvements here, just a literal description of the current 'process'
- [x] Somoene else goes through this process, and makes *changes to the document as they go* to make sure it is accurate
- [x] Notify CS&S that this has been updated for January, February, and March
- [ ] This document gets reviewed and merged into our documentation

### Updates and actions

There's a draft of this in https://hackmd.io/liA3hR2QQmm9FqLE201RVA

**Comment by yuvipanda** [comment]
This is ready to go from my perspective - the linked hackmd is complete enough for someone to take a shot at this.

**Comment by yuvipanda** [comment]
Given that march is now complete, I've just updated the title to have this be done for Jan - March.

**Comment by consideRatio** [comment]
@yuvipanda I've updated AWS Jan, Feb, March, and GCP March - went smooth. I did some detail updates for AWS.

### Question 1

For GCP, what do we do with `[Charges not specific to a project]` in the exported .csv file?

### Question 2

> Notify CS&S that this has been updated for January, February, and March

Is this on me or someone else? I need to be onboarded into this process to do it myself I think - otherwise I'll probably fail to convey relevant info in a way they expect to CS&S.

---

> This document gets reviewed and merged into our documentation

I'll assume I'm the driver of this, I'll see if I can find someplace where it could make sense to integrate in our docs.

**Comment by yuvipanda** [comment]
@consideRatio yay thank you! Thanks for doing March on GCP too.

I think for 'notify CS&S', right now that's:

1. Go to the `#billing` channel in 2i2c slack (this is shared with CS&S) (just added you)
2. Tag Elliot and let her know the spreadsheet has been updated.

That's it.

**Comment by yuvipanda** [comment]
@consideRatio and re: documentation, https://github.com/2i2c-org/infrastructure/pull/3851 is the equivalent GCP PR that @GeorgianaElena made. Perhaps right below that?
