### ISSUE TITLE
Handle healthchecks hubs with binderhub-service set up to launch

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4167]
Per https://github.com/2i2c-org/infrastructure/issues/4133#issuecomment-2140722573, our health check scripts currently fail when used on a JupyterHub setup to be in service of binderhub for launching.

Here's a failing health check: https://github.com/2i2c-org/infrastructure/actions/runs/9307796142/job/25620397449

```[tasklist]
- [x] Temporarily skip these tests so that CI doesn't fail
- [x] Figure out what a real health check for this setup should be (See https://github.com/2i2c-org/infrastructure/pull/4263 and comments below on an alternative plan for binderhub ui and null authenticator setup)
- [x] Implement/skip real health check
```

**Comment by GeorgianaElena** [comment]
> Figure out what a real health check for this setup should be

I've been thinking about this today and I couldn't come up with an answer to this, so instead of me going into various rabbit holes trying to come up with something, I'd really appreciate some direction from you @yuvipanda.

My findings so far are that:

- we need a policy on what goes into the `cluster.yaml` file under `hub.domain`. Is it the hub domain or the binderhub one? (this entry is currenlty being used in our health checks)

- running the current health checks on an authenticated binderhub like the demo one that's in the 2i2c cluster actually works but it bypasses binderhub I believe

_I think_ a solid health check would mean sending an API request to binderhub directly to build and launch an image then execute a simple notebook on the server. BUT, I don't think that's easy as we won't have a library that deals with cleaning up the users and servers afterwards and we will need to do that ourselves otherwise we'd run into troubles. So this sounds as a viable solution to me but will require more work than I'd expected initially I believe. Should I go ahead on this path?

**Comment by yuvipanda** [comment]
First, I just *absolutely* love this comment @GeorgianaElena! This is exactly the kind of team conversation I want to be a part of :)

In ephemeral hubs where binderhub also controls launching, there are three things to test:

1. Does building repos work?
2. Can binderhub launch built repos?
3. Can JupyterHub spawn servers?

Our health checks currently only test for (3) and not (1) and (2). We do have upcoming work (with Project Pythia and VEDA) to do (1) and (2) as well - I'll have a productboard link soon.

So I would say that to complete *this* task, we should define it to only test (3). So it'll be on par with our other hubs.

I think the action items here are:

1. Make sure that our existing health checks (which only check for spawning) *do* work, with and without authentication.
2. Create an issue to keep track of augmenting our health checks to account for the entire build and launch process.

I'll work on (2), and you can use this to track (1). How does that sound?

**Comment by yuvipanda** [comment]
@GeorgianaElena thank you for digging in in https://github.com/2i2c-org/infrastructure/pull/4263.

Based on the complexity I see there, I think we should take a different approach.

In cases where BinderHub UI is enabled (auth or not), let's just skip our existing health checks. I'll link that to the upcoming feature set for using this for CI/CD (hopefully I'll have that soon).

So definition of done for this issue should now be:

1. If BinderHub UI is enabled, we don't run our health checks

Hope that makes sense to you!

**Comment by yuvipanda** [comment]
https://github.com/pangeo-gallery/binderbot is the existing bits that use the binderhub API (for building *and* launching) for CI. There's a project pythia meeting next week where we will discuss this some more, and there will be a new product dev feature that we will spec out based on that. That can also be used to test our binderhubs themselves.

So with that, we can scope this issue to 'do not fail our health checks'. All the investigative work done here has shown us that adopting our current practices to these installations is going to be too much work, and not the right direction.

**Comment by GeorgianaElena** [comment]
@yuvipanda, I've updated the PR with https://github.com/2i2c-org/infrastructure/pull/4263#issuecomment-2182564919 and we're skipping health checks for  BinderHub UI + null authenticator. Based on your feedback, after I merge that, I will close this issue and track future work in other places, is that correct?
