### ISSUE TITLE
Decide on the 'home page' flow when deploying ephemeral hubs with binderhub-service showing the binder-ui

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4168]
**Update:** Decision has been made https://github.com/2i2c-org/infrastructure/issues/4168#issuecomment-2141701666

If you go to https://binderhub-ui-demo.2i2c.cloud/ right now, you first see this:

<img width="1000" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/436c9746-32db-4296-bbc5-5a447950cd0d">

This is our custom 2i2c homepage for all hubs. Let's call this the 'signed out home page'.

Once you log in, you see this:

<img width="1231" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/1e6b161e-856f-4539-a481-8e360c1cdb94">

Let's call this 'the signed in home page'

So there are really *two* home pages.

We need to decide what we want the experience to be.

# Option 1: One home page only

In this case, the 'signed out' home page is just not shown. If you go to https://binderhub-ui-demo.2i2c.cloud/, you're immediately redirected to the login system if you aren't already logged in, and then get sent to the 'signed in' homepage. If your authentication fails, you see just an error message and nothing else.

Engineering note: This can be accomplished with the `auto_login` trait on the hub (or similar - see what we do for utoronto). 

# Option 2: Two home pages (**WINNER** [comment](https://github.com/2i2c-org/infrastructure/issues/4168#issuecomment-2141701666))

In this case, we continue the current pattern, so users have a place to 'land' even if they are not authenticated. We would have to develop a slightly modified 'signed out home page'. Otherwise nothing changes.

Engineering note: This would require a new branch in https://github.com/2i2c-org/default-hub-homepage, similar to the one we have for hubs that use dummyauthenticator

# Decision making process

This feels like a decision that should be guided by product, so I'll reach out to @Gman0909 to help make this choice. Once done, I'll create appropriate engineering tickets to move forward.

**Comment by colliand** [comment]
I

**Comment by yuvipanda** [comment]
@colliand I'd like to scope this issue to this very specific question - can you move this to a different issue, and we can tackle that there?

**Comment by consideRatio** [comment]
Ephemeral hubs with binderhub-service can come in two forms right? Binderhub ui or fancy profiles based - but this is solely scoped for binderhub-ui use right?

I ask to ensure we communicate consistently and distinctively about these so that they aren't mixed up when we and others speak about this over time

**Comment by yuvipanda** [comment]
> but this is solely scoped for binderhub-ui use right?

correct!

**Comment by Gman0909** [comment]
We have white labeling on our roadmap, so we want to offer institutions the option to customize their landing pages and other hub touch points with their brand, so having the recipient of an ephemeral hub link land on a custom version of the first home page would be the way to go. Not least because dropping someone into a login screen with no context might be jarring, and even look somewhat suspicious. 

The new Planetary Computer demo landing page (below) is a perfect example of a tidy, uncluttered, minimalist landing page that provides context and a clear call to action without being distracting. Now imagine that with the relevant community logo instead and you'll get more of a sense of why having that additional bit of context and reassurance when following a link someone sent you is a good thing. 

The custom logo can be out of scope for this, but keeping a minimal home page with a login button is a prerequisite. 

![image](https://github.com/2i2c-org/infrastructure/assets/12699608/fa0f077d-515b-465c-8b46-5e995e11a85e)

**Comment by yuvipanda** [comment]
Alright, so @Gman0909 has made the choice. I've done the following:

1. Opened #4195 to allow disabling everything south of 'login to continue'
2. https://github.com/2i2c-org/infrastructure/issues/4197 accounts for setting this up for binderhub-ui-demo
3. Recorded this choice in #4169 

With that, I'm going to mark this as closed. Thanks, @Gman0909!
