### ISSUE TITLE
Google group access to persistent buckets

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#4281]
Opening a new ticket to capture the question below from a ticket that will be closed

---

Thanks for the explanation Erik, I will capture this insight for our Product board. 

Regarding cloud permissions, do you happen to know what the Google Group @sgibson91 [mentioned above](https://github.com/2i2c-org/infrastructure/issues/4214#issuecomment-2165171440) is for then? Here are the [relevant infrastructure docs](https://infrastructure.2i2c.org/howto/features/buckets/#id2).

_Originally posted by @jnywong in https://github.com/2i2c-org/infrastructure/issues/4214#issuecomment-2188488011_

**Comment by consideRatio** [comment]
> https://infrastructure.2i2c.org/howto/features/buckets/#allowing-authenticated-access-to-buckets-from-outside-the-jupyterhub

It seems to be for this exact situation, I just wasn't aware - sorry for the confusion!

Looking at details, it seems that there is a google group setup for access to leap as well. I figure whats needed is to verify that the access using this group procedure works all the way - and what I did may bypass your ability to test it - because you were granted permissions in another way.

I think the task concretely is to tweak/verify a procedure to work against a bucket when being granted permissions via the procedure in the listed docs.

**Comment by jnywong** [comment]
No worries, I am glad we are getting clarity on this mechanism!

That's fine, I can add a dummy test account to the Google group to test this procedure again.

**Comment by jnywong** [comment]
We have established that `serviceusage.services.use` project permissions are required to allow application default credentials (ADC) to be recognized.

- [ ] @consideRatio to update the Infrastructure Docs with note on `serviceusage.services.use`
