### ISSUE TITLE
[Spike] [90min *max*] Understand what is needed to enable eventlog aggregation for hubs with BinderHub UI

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4309]
In order to understand how our BinderHub UI deployments are actually being *used*, we need to enable the (privacy preserving) telemetry that BinderHub provides. There's a public facing website at https://archive.analytics.mybinder.org/ for the mybinder.org version. We won't need a public facing website, but we should collect this data from all our deployments.

This issue is about doing a *timeboxed* spike to collect more information about what is needed for us to enable this for our installations.

https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/mybinder/values.yaml#L202

is the config that enables this in mybinder.org, and is probably a useful starting point.

**Comment by consideRatio** [comment]
Focusing on the collection and retention of data rather than presentation, I'll need to look into misc things and learn about them.

## mybinder.org chart inspection

The [config linked by Yuvi in the description](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/mybinder/values.yaml#L198-L226) works against a centralized google stackdriver destination, and access for curvnote and ovh federation members to that is provided by a GCP service account mounted and detected via GOOGLE_APPLICATION_CREDENTIALS environment variable.

The following top level configuration sections for the mybinder meta chart involves containers running in the cluster.

- `matomo` ([docs](https://mybinder-sre.readthedocs.io/en/latest/components/matomo.html)) (only runs on the GCP mybinder.org federation member) - frontend events, not of interest
  It is collecting data from frontend webpages, this is not related to the telemetry events emitted by the binderhub software we care about in this issue. The binderhub frontend is modified via `BinderHub.extra_footer_scripts`, injecting the motomo frontend event collection.
- `analyticsPublisher` (only runs on the GCP mybinder.org federation member)
  - archiver.py docstring writes:
    > Read event logs from stackdriver & export them to Google Cloud Storage
- `gcsProxy` (only runs on the GCP mybinder.org federation member)
  I think it helps `analyticsPublisher` to access buckets on GCP.

## related docs

- https://binderhub.readthedocs.io/en/latest/eventlogging.html#event-logging
- https://mybinder-sre.readthedocs.io/en/latest/analytics/index.html

## Conclusions

MyBinder.org has its federation members binderhub software export event data to a single google stackdriver destination (stackdriver is now called Google Cloud operations), and does so via:
- [`binderhub.extraConfig.01-eventlog`](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/mybinder/values.yaml#L198-L226)
- [`eventsArchiver.serviceAccountKey`](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/mybinder/values.yaml#L633-L635) -> A [mybinder chart k8s Secret template](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/mybinder/templates/events-archiver/secret.yaml#L12) -> [`binderhub.extraVolumes` and `binderhub.extraVolumeMounts`](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/config/curvenote.yaml#L38-L45) mounting -> [`binderhub.extraEnv.GOOGLE_APPLICATION_CREDENTIALS`](https://github.com/jupyterhub/mybinder.org-deploy/blob/b804c1f846814a635a869912eec477012d32d9e8/config/curvenote.yaml#L31)

### Central destination or project specific destination?

We have multiple binderhub-ui deployments, and if we want we can setup a central stackdriver destination to accept data without doing something new and mimicing mybinder.org and its federation members in AWS/OVH/GCP. We could then also process that centrally to end up in a bucket like mybinder.org does via `analyticsPublisher` and `gcsProxy` in the GCP federation member.

Drawbacks of doing that involves coupling to GCP specifically and coupling to a centralized project etc managed by 2i2c rather than the communities cloud infra.

Currently we have binderhub-ui hubs at:
- 2i2c cluster (GCP)
- opensci cluster (AWS)
- hhmi cluster (GCP)
- projectpythia (AWS)

So concretely, to centralize would mean to make them all submit events to one destination. If we decide to not submit data to a central location, projectpythia and opensci being on AWS can't reasonably rely on logic to submit data to GCP's services but should submit to something in their own AWS cloud infra instead. I think [AWS EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html) (formerly AWS CloudWatch Events) think may be the relevant service to lean on if so.

## Followup work ideas

- Clarify if we aim to collect these events centrally for all communities - if so things are quite clear technically on how to proceed but has various open questions related to R2R.
- Assuming we look to collect data within communities cloud infra, we need to handle doing it in AWS accounts where we can't replicate exporting to stackdriver.
  
  We could setup something like AWS EventBridge for that perhaps, but we could also instead try to deploy something in-cluster agnostic of additional services like GCP Google Cloud Operations (StackDriver) or AWS EventBridge.

**Comment by consideRatio** [comment]
Spike investigation started 8:15, ended 9:40 - 85 minutes!

**Comment by yuvipanda** [comment]
Awesome job, @consideRatio! Let's dedicate some time during our next 1:1 for refining some tasks out of this spike?
