### ISSUE TITLE
Support creating multiple Filestore instances via Terraform on GCP

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4334]
In order to do https://github.com/2i2c-org/infrastructure/issues/4257, we must be able to create multiple GCP filestores instances on Terraform. That way, we can perform the steps in https://github.com/2i2c-org/infrastructure/issues/4257#issuecomment-2196189509 and decomission the old filestore, rather than fiddle around with `terraform state`.

**Comment by sgibson91** [comment]
Ah pfft. I was really proud of the fix, but now I don't think it will work.

The original idea would be that we'd do something like this:

1. Original filestore config:

   ```
   filestores = [
      { filestore 1 ... }
   ]
   ```

2. Add a second filestore:

   ```
   filestores = [
     { filestore 1 ... },
     { filestore 2 ... }
   ]
   ```

3. Remove the original filestore:

   ```
   filestore = [
      { filestore 2 ... }
   ]
   ```

The problem is that because this method is _index based_, the index changing would force the filestores to recreate anyway. For new or existing clusters! Boo!

My original idea used a map of maps and looked a lot nicer in the code too. So the config is something like:

```
filestores = {
  filestore_1 = {
    blah ...
  },
  filestore_2 = {
    more blah ...
  }
}
```

This would mean that when we removed filestore_1, filestore_2 wouldn't be forcefully recreated. But, this breaks for all of our existing clusters (trying to force them to recreate) because we are trying to move them from index `[0]` to index `["filestore_1"]`.

I don't think we're going to get around this without playing with `terraform-state`, at least for this initial setup.

**Comment by sgibson91** [comment]
I just confirmed my hunch on the catalyst-latam project

**Comment by yuvipanda** [comment]
@sgibson91 My suggested solution (and we do something like this for `hub_cloud_permissions` with `hub_namespace`) is:

1. Implement map of map as you suggested as solution
2. Require explicitly specifying the name of the filestore in the map
3. Explicitly set for all existing filestores the existing name, so they will not be recreated
4. As an option, default to the name of the map for the filestore name, so we don't have to repeatedly specify it.

**Comment by sgibson91** [comment]
Ah, that's what I tried (or rather setting a name suffix, and if it was null, default to what we had ... I wish I hadn't blitzed my branch I had that on!). The name change isn't the problem, it's the _index_ change that causes the recreation.

The _index_ changes from `[0]` to `[map_key]` (even though the name remains constant) and that forces a recreation. We will probably have to transfer state from the 0 index to the new map key index.

I'll recreate my first attempt on Monday morning and we can meet and I'll walk you through it if I'm still not making sense.

**Comment by sgibson91** [comment]
I swapped to using a map of maps in https://github.com/2i2c-org/infrastructure/pull/4373, but we still have to use `tf state mv`, which I have implemented for the `pilot-hubs` cluster.
