### ISSUE TITLE
Clarify in documentation how to "rename users" as is mentioned

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#435]
[This page](https://pilot-hubs.2i2c.org/en/latest/howto/configure/auth-management.html) mentions how to "rename users", but I'm very uncertain where and how to do that.

JupyterHub has a concept of a user and a name, and could probably be updated in its database. But, then the username will no longer match a home folder name and such. So, I wonder if the rename is suggested to be done somewhere else?

**Comment by damianavila** [comment]
Mmm.... that is a good question!

> But, then the username will no longer match a home folder name and such.
Yep, that was my immediate thought after reading the beginning of your question...

@yuvipanda any light for us 😉 ?

**Comment by damianavila** [comment]
Yep, it is related, IMHO.
You have the user's content in the persistent disk at `/exports/home-01/<hub-name>/<user-name>`.
If you change the username, you need to change the `<user-name>` stuff there as well.
What @yuvipanda is asking in that PR, IIUC, is to mount `/exports/home-01/<hub-name>` into some admin-only place (`/home/jovyan/shared/user-homes`) so they can do the renaming by themselves... Otherwise, we (2i2c eng) need to get into the persistent disk (through the NFS Server) and do the change by ourselves.

**Comment by consideRatio** [comment]
I got a 404 when looking at the link, and searching for "rename users" in the code base didn't make something show up.

I'll close this!
