### ISSUE TITLE
[Deadline Wed July 10] Make jupyter-launcher-shortcuts support JupyterLab 4

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4366]
Based off the partnerships request in https://2i2c.slack.com/archives/C076Y57HRC6/p1720207761295029. 

Communities want to add additional links in their image to tiles that do whatever as part of the jupyterlab launcher.

```[tasklist]
### Tasks
- [x] Review and merge https://github.com/2i2c-org/jupyter-launcher-shortcuts/pull/24
- [x] Make a release on PyPI
```

**Comment by yuvipanda** [comment]
Separately, I'll work on migrating that repository to https://github.com/jupyterlab-contrib/ which is a better home for it.

**Comment by yuvipanda** [comment]
For https://github.com/2i2c-org/jupyter-launcher-shortcuts/pull/24, I'd like the goal to be to *test* and merge, rather than *review* (to understand all the details of how jupyterlab extensions work).

**Comment by yuvipanda** [comment]
I've invited @consideRatio to the PyPI project as well.

**Comment by agoose77** [comment]
I can take a pass at this next week if that would be helpful?

**Comment by consideRatio** [comment]
I took a pass and think it could be merged as it is or after further review by @agoose77 who brings significant jupyterlab extension know-how that I lack.

Before release I'd like a decision to be made about the project's support for use with the classical notebook UI. With the PR its broken for both v6 and v7 where the readme is updated to document that v7 may be fixed in the future, and I've opened https://github.com/2i2c-org/jupyter-launcher-shortcuts/issues/25 about that. @yuvipanda can you make a call about if we should fix function against notebook v7 before release, to not do that, or do something else?

**Comment by consideRatio** [comment]
@yuvipanda I asked @agoose77 about publishing to npm:

> Do you know if publishing to NPM is considered relevant for JupyterLab >= 4 compatible pre-built extension, or if people developing extensions stopped doing so after packaging things along with the python package and no longer supporting older JupyterLab versions?

> Hey Erik, people still publish to npm. It allows you to pre-bake the extension into the JupyterLab installation and perform tree shaking
> It's not the end of the world if you don't publish it, but I'd recommend it

Could you grant me permission in [the npm project](https://www.npmjs.com/package/jupyterlab-launcher-shortcuts) as well to publish there also?

**Comment by yuvipanda** [comment]
@consideRatio I've invited you as a maintainer on npm!

@consideRatio we should not try to fix issues with notebook 7 before release.

**Comment by yuvipanda** [comment]
> I took a pass and think it could be merged as it is or after further review by @agoose77 who brings significant jupyterlab extension know-how that I lack.

You can make that call here @consideRatio, as long as we make it before the deadline.

**Comment by consideRatio** [comment]
I opted to add release automation and related docs instead of relying on my personal pypi/npm access. I took notable time for me to get the npm publishing part right.

Version 4.0.3 is now out in PyPI and NPM and should work to install via pip (but not yet conda-forge, see https://github.com/conda-forge/jupyter-launcher-shortcuts-feedstock)

**Comment by consideRatio** [comment]
I gave this 5 story points retroactively as I ended up investing notable amount of time and work to get this working.
