### ISSUE TITLE
Retain binderhub analytics events

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4423]
As part of https://github.com/2i2c-org/infrastructure/issues/4365, binderhub events now flow into a log in a separate google cloud project made just for this (https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fbinderhub-event-logs%2Flogs%2Fbinderhub-event-logs%22;cursorTimestamp=2024-07-12T19:57:06.488977Z;duration=PT1H?referrer=search&project=binderhub-event-logs). However, this is retained only for 30 days.

What we want to *do* with this data is to be determined eventually in collaboration with partnerships. In the meantime, we should take efforts to not lose it after 30 days.

Google Cloud logging supports [routing](https://cloud.google.com/logging/docs/export/configure_export_v2) logs to a specific destination where they can survive long term. Since we want the most cloud agnostic option, that would be routing it to a [cloud storage bucket](https://cloud.google.com/logging/docs/export/storage)

This task is to create configuration so that *only* the logs of these launches (identified by `logName="projects/binderhub-event-logs/logs/binderhub-event-logs"`) get archived into a new storage bucket (let's name it `binder-2i2c-events`). This can be done in the cloud console, no terraform needed at this moment.

**Comment by consideRatio** [comment]
I think i may have already done this, but not confirmed it works because i was low on time and it said it was getting done every hour.

I also changed the default log storage bucket to retain things for two years in this project in case it fails to transfer to the dedicated bucket for binderhub event logs.

**Comment by consideRatio** [comment]
![Screenshot_20240712-224631](https://github.com/user-attachments/assets/7249ca86-670f-44b7-95f5-fc64c1aa8c0c)

Log router + log storage was things i tried using for this

**Comment by GeorgianaElena** [comment]
@consideRatio, I believe your setup was working indeed 🚀 It was however storing the logs into a logs into a Cloud Logging Bucket, and @yuvipanda's request was for a cloud storage bucket.

I just createad a new storage bucket with the name `binder-2i2c-events`, with the following configuration:
https://console.cloud.google.com/storage/browser/binder-2i2c-events;tab=configuration?project=binderhub-event-logs&supportedpurview=project
<img width="575" alt="Screenshot 2024-07-16 at 13 34 39" src="https://github.com/user-attachments/assets/32e587a9-06ff-4c2a-961f-b9af62edd3e5">


And then  re-configured the log router that @consideRatio created to route the logs into the cloud storage bucket rather than the log bucket.

<img width="476" alt="Screenshot 2024-07-16 at 13 36 51" src="https://github.com/user-attachments/assets/36997051-aef7-45ac-9d14-2da70daeb794">

**Comment by GeorgianaElena** [comment]
@yuvipanda, before considering this done, can you please confirm that:

- [ ] the bucket's config looks good to you as I had to make some decissions like making it multi-region etc
- [ ] is ok to delete the logs bucket that Erik created (it currently has a few days worth of data)?

**Comment by yuvipanda** [comment]
@GeorgianaElena looks good to me! You can delete the old log bucket (which I assume no longer receives events), and close this ticket once you confirm new events have come to the cloud bucket!

**Comment by GeorgianaElena** [comment]
Data is in the new bucket, so deleting the old one. Thank you @yuvipanda!

<img width="1362" alt="Screenshot 2024-07-17 at 11 38 14" src="https://github.com/user-attachments/assets/080a5d10-e05c-4259-93dd-5e3113d18d44">
