### ISSUE TITLE
[Spike: 2h] Fix storage backups for Azure clusters

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4487]
This is a follow-up to https://github.com/2i2c-org/infrastructure/issues/624 and is blocking https://github.com/2i2c-org/infrastructure/issues/4426

While working on validating that restoring backups works, I couldn't find any backup instances, so we need to figure out what's missing to get that working. 

I suspect https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_protected_file_share is the missing bit, but we should verify this

### Tasks

- Explore adding https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_protected_file_share to our terraform code and if this results in backups being created

### Definition of done

Monitor backup creation in `Backup Center -> Backup instances` of the the Azure Portal. Either:
- [ ] new backups are being created and the issue is resolved, or;
- [x] backups are not being created and further spikes are required.

**Comment by sgibson91** [comment]
I tried to add the suggested terraform resources but with no luck. Details of my experiment can be found in #4627 

Eventually, I tried configuring the backups manually in Azure Portal, to see if I could figure out why the file share wasn't being discovered. It turns out that NFS shares are not supported for backup! So our terraform config will _never_ work! https://werecomputersamistake.com/

![Image](https://github.com/user-attachments/assets/35ce3b16-f022-4e51-b616-66e760a086e0)
