### ISSUE TITLE
configure OAuth flow with compliant OAuth URI validation rules 

### ISSUE THREAD

**Issue by aculich** [2i2c-org/infrastructure#451]
Hi @GeorgianaElena could I get your help with this request that came to me from the Mills folks?

# Summary

Google sent an email saying:

> Hello Google Developer,
>
> We are writing to let you know that you have active OAuth redirect URIs and JavaScript origins in your Google Cloud project that are not in compliance with Google’s OAuth URI validation rules. All noncompliant active URIs will be removed, along with their origins, by September 13, 2021.

# User Stories

All end users trying to log in will be unable to do so, because all noncompliant active URIs will be removed, along with their origins, by September 13, 2021.

# Acceptance criteria

OAuth flow has been configured to use compliant [redirect URIs](https://developers.google.com/identity/protocols/oauth2/web-server#uri-validation) and [Javascript origins](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#origin-validation) and that logins have been tested by Mills faculty and IT admins before August 11th.

# Important information

> What do I need to do to be compliant?
>
> Please update your app and OAuth configuration in the Google Developer Console to use redirect URIs or JavaScript origins that are compliant with the OAuth URI validation rules by September 13, 2021.

# Tasks to complete

The following Google Cloud project(s), which has/have registered URIs and origins that are out of compliance, and which will be removed if you do not update your OAuth flow to use compliant redirect URIs and Javascript origins by September 13, 2021: 

- Project ID: ucb-data-science-collaboration
- Client: 859230276709-ulo4jank781cf0rfdfnclg3hsdvjji6c.apps.googleusercontent.com
-  URI: http://datahub.mills.edu/hub/oauth_callback

**Comment by GeorgianaElena** [comment]
Hey @aculich!

> The following Google Cloud project(s), which has/have registered URIs and origins that are out of compliance, and which will be removed if you do not update your OAuth flow to use compliant redirect URIs and Javascript origins by September 13, 2021:

>    Project ID: ucb-data-science-collaboration
    Client: 859230276709-ulo4jank781cf0rfdfnclg3hsdvjji6c.apps.googleusercontent.com
    URI: http://datahub.mills.edu/hub/oauth_callback

I believe the URI mentioned `http://datahub.mills.edu/hub/oauth_callback` is noncompliant with the OAuth URI validation rules because it uses `http` instead of `https`.

However, I looked over what requests are being made when loging into the mills hub and didn't find any request to `datahub.mills.edu/hub/oauth_callback` that didn't use `https`.

Also, here are the Allowed Callback URLs registered for the mills hub in Auth0 (they seem to respect the rules):
- https://mills.cloudbank.2i2c.cloud/hub/oauth_callback
- https://datahub.mills.edu/hub/oauth_callback

I'm wondering if the URI mentioned as being not compliant was somehow registered by mistake when I played around with deploying the mills hub and it's not actually being used anywhere.

@yuvipanda, what do think? Is there anything else that I should be checking or anything that I'm missing from the workflow?

**Comment by yuvipanda** [comment]
From looking at this:

```
Project ID: ucb-data-science-collaboration
```

I think this was maybe from a previous setup? We don't have access to that Google Cloud Project, and we only use auth0. So I'm not sure what we can do. @aculich do you have access to that project?

**Comment by aculich** [comment]
@yuvipanda @GeorgianaElena aha, thanks for sleuthing this one!

I think you're correct that this was probably from an old setup and, likely, they can just delete that old project.

In any case, from your perspective it sounds like what you have configured will continue to work just fine without any changes on your end?

**Comment by yuvipanda** [comment]
> In any case, from your perspective it sounds like what you have configured will continue to work just fine without any changes on your end?

@aculich yep, that's  correct!

**Comment by yuvipanda** [comment]
We no longer use Google directly, so this is all good.
