### ISSUE TITLE
Reference: information about AWS clusters without cost attribution enabled.

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4885]
The following clusters were created without `2i2c.org/cluster-name` tag applied to node groups, or other less relevant resources like EKS plugins.

- [x] catalystproject-africa
- [x] earthscope
- [x] gridsst
- [x] jupyter-health
- [x] jupyter-meets-the-earth
- [x] kitware
- [x] nasa-cryo
- [x] nasa-ghg
- [x] nasa-veda
- [x] openscapes
- [x] opensci
- [x] projectpythia
- [x] smithsonian
- [x] ubc-eoas
- [x] victor

This issue is referenced by documentation being written in #4873, where we can check off clusters over time, and should be able to close with the completion of #4878.

**Comment by GeorgianaElena** [comment]
While doing #4878 @consideRatio and I discovered that clusters running on `k8s 1.29` don't have the `2i2c.org/cluster-name` applied to nodegroups, so they qualified for recreating their nodegroups in order for the tag to be picked up (per step 3 of https://infrastructure.2i2c.org/howto/cost-attribution/aws/#practical-steps).

However, k8s 1.29 does set other tags that are also being picked up by our cost allocation dashboard, namely `alpha.eksctl.io/cluster-name` and `kubernetes.io/cluster/{CLUSTER_NAME}`

https://github.com/2i2c-org/infrastructure/blob/2aa8c917fd399733b042928418b394a22a340c6a/helm-charts/aws-ce-grafana-backend/mounted-files/const.py#L54-L75

This means that the nodegroups weren't recreated this time, so they don't have the `2i2c.org/cluster-name` tag, which is fine from a cost attribution point of view because of the other two that are present. As far as we know currently we're not assuming this tag is present on the nodegroups, so this issue can be closed.

Note that once we'll upgrade the k8s version and recreate the nodegroups anyway, the `2i2c.org/cluster-name` will be automatically added. So no specific action needs to be taken at this moment. Closing the issue.
