### ISSUE TITLE
AWS cost attribution: put each hub in earthscope into its own user nodegroup

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#5100]

**Comment by consideRatio** [comment]
The r5.xlarge staging nodegroup wasn't re-created successfully, I figure its because the cloudformation stack representing it was pending deletion still while the nodegroup create command ran, where then `eksctl` would silently mention that it was already created (but it was actually pending deletion still!).

**Comment by sgibson91** [comment]
r5.xlarge staging nodegroup just scaled up fine for me - closing
