### ISSUE TITLE
Formula for calculating hub-specific cloud costs on a shared cluster

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#730]
### Context

If we wish to host hubs for multiple communities on the same clusters, and if we wish to pass-through cloud costs directly to communities that we serve, then we need a way to track cloud costs within a cluster per hub. Without this, we won't be able to fairly split the cloud costs we pay on behalf of these communities, and we may also be losing money ourselves.

We need a way to turn the monthly cloud bill for a collection of JupyterHubs into a single number for each hub. This means:

Develop and document the method we'll use to split up individual hub costs on a shared cluster. This has two steps to it:

- Define what _usage_ means (AKA, how to define that one hub has used twice as much resources as another)
- Calculate the per-hub _usage_ each month.
- Break down the monthly cost per hub based on its per-hub usage

### Proposal: use usage based on memory

Here's a proposal:

- For each month, for each cluster, we calculate the total amount of RAM that was utilized on that cluster
- We calculate how much RAM was used by each tenant (each hub) on the cluster
- For each community, their cloud bill is `(hub_RAM_used / total_cluster_RAM_used) * cloud_bill_for_cluster`

This assumes that RAM is the largest driving factor of cloud costs, which is reasonable for most communities. It will break down if a community uses a lot of *storage* (in that case, some hubs would be charged more than we want, and others less), but this stop-gap billing strategy can intentionally not address that use-case so that we can iterate on this in the future. I think that this is a good compromise, because we (1) tie cloud bills for each hub to a reasonable estimate of their usage, and (2) entirely cover our cloud costs.

### Updates

- **2021-11-01** - We had a helpful conversation about this in https://github.com/2i2c-org/team-compass/issues/277 along with several ideas of what / how to track

#### 2022-03-11: plan to give this a shot

- [ ] Determine the information we'd need to generate a little "report" about cloud usage for a hub in a given month
- [ ] Figure out how to programmatically pull usage information from Prometheus
- [ ] Figure out how to programmatically pull the cloud bill for a cluster
- [ ] Make this available as a nice "dataset" that we people could use to generate reports or invoices
- [ ] Package this process up so that it's repeatable across deployments (e.g. so both 2i2c and Berkeley could use it)

**Comment by choldgraf** [comment]
I'm labeling this one as high-impact because we need *some* answer for this in order to be able to know how much to bill each hub on our cluster (unless we want to just send a bill that is `cluster_total / n_hubs`)

**Comment by sgibson91** [comment]
I think any solution we come up with here will be dependent on our grafana graphs. One thing we could do is work out a cost per pod per time-increment and then integrate under our pods over time graph over the billing period. Maybe tack on a "base cost" of things like the hub pod that are always running.

**Comment by yuvipanda** [comment]
The other option is to use [GKE usage metering](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering). https://medium.com/pangeo/pangeo-cloud-costs-part1-f89842da411d is the prior art here, although I don't think @jhamman has had time to work on it since. 

I like the grafana idea a lot as well, as it will work across cloud providers. 

There are two primary conceptual issues to work through:

1. We pay cloud providers for *nodes*, rather than pods. So if we have a 64GB node running but there's only 5 pods of 1GB each running on it, how do we cost that? 
2. We overprovision user pods by making the memory limit a multiple of the memory request. So if we have 100 users with 1GB limit but 256GB guarantee, they might all fit on one node because it is unlikely (quantifiable in some way I'm sure) that *all* of them go over 256GB at the same time. I know we wrote up a more complex issue about this earlier with graphs but I can't find it right now...

However, maybe we don't need to do all that to begin with! We can just hit prometheus (which is where grafana gets its data from), and just follow @sgibson91's idea of a base cost + cost per pod per time increment. Perhaps the cost per pod per time increment can be just a multiple of what we get from [GCP's VM pricing](https://cloud.google.com/compute/vm-instance-pricing#general-purpose_machine_type_family)? Looking at n1 instances (which is what we use) before discounts, it's $0.004237 / GB hour and $0.031611 / vCPU hour...

**Comment by choldgraf** [comment]
### Update: cloud cost ideas

We had a helpful conversation about this in https://github.com/2i2c-org/team-compass/issues/277 along with several ideas of what / how to track

**Comment by colliand** [comment]
I am curious to know if the following cost sharing partition make sense.
![cloud-cost-partition](https://user-images.githubusercontent.com/1879041/142804096-d7ff7ab1-ea65-4db7-898f-4bfd1d4b6612.jpg)

(The image was generated as a screenshot from [this HackMD note](https://hackmd.io/G2Cq1Ya4ShiDn7naSh7Kbw?view).)

If I understand the comments from @yuvipanda and @choldgraf  in this issue, #277, and #262, we expect:

+ RAM-Hours are a good proxy for a customer's fair portion of cloud costs.
+ Prometheus provides a way to measure total RAM-hours and each customer's RAM-Hours.

**Comment by yuvipanda** [comment]
The extra question is, what do we do about the unused RAM we are paying for, that no customer is using at that moment? We will never be at 100% utilisation.

**Comment by colliand** [comment]
The extra unused RAM-Hours, storage costs, cpu costs, and perhaps other cost dimensions contribute to total cost D. We partition D proportionally based on RAM-Hours used by customers. If the extra costs scale roughly with RAM, this seems fair and recovers 100% of the monthly cloud costs.

**Comment by yuvipanda** [comment]
@colliand ah, great. I think we'll need to add storage and CPU too there somehow though. Can it be RAM-CPU-Storage(GB) as a unit?

**Comment by colliand** [comment]
I may be missing your point. The total cost paid for the hub is D. That cost is what 2i2c must pay to the cloud vendor. We want to fairly chop that up and assign portions-commensurate-with-usage to the customers that use the hub. 

Based on the discussions, I understand that RAM-usage-per-customer can be extracted from Prometheus and that we expect RAM-usage is a fair proxy for usage cost. This won't be the case if one customer uses tons of storage or cpu compared to the others. 

Over time, depending on instrumentation, we may be able to build a better proxy for cost partitioning that RAM usage. 

I'm aiming here to land on a story  that can be explained to prospective customers. I feel like I have that provided I'm not saying anything that seems super wrong. 

The key assumptions: 
1. RAM usage per customer per month can be measured by 2i2c. 
2. RAM usage per customer should be a decent proxy for overall cost per customer.

**Comment by choldgraf** [comment]
### Proposal: calculate cloud cost based on RAM as a short-term solution

(this is a summary of what I think @colliand is proposing above).

- For each month, for each cluster, we calculate the total amount of RAM that was utilized on that cluster
- We calculate how much RAM was used by each tenant (each hub) on the cluster
- For each community, their cloud bill is `(hub_RAM_used / total_cluster_RAM_used) * cloud_bill_for_cluster`

This assumes that RAM is the largest driving factor of cloud costs, which is reasonable for most communities. It will break down if a community uses a lot of *storage*, but this stop-gap billing strategy can intentionally not address that use-case so that we can iterate on this in the future.

If others are OK with this, then I suggest we:

- Create an issue about implementing the simplified cloud costs estimation above
- Create another issue about the improvements we want to make to this process (e.g., factoring in more resource usage like storage)

**Comment by colliand** [comment]
Yes, exactly what I suggested. Thanks Chris!

**Comment by choldgraf** [comment]
### Update: This could be useful for Pangeo

Just a note that I had a conversation with @rabernat that is related to this issue. We were discussing the challenge of having universities requiring university-specific emails in order to run their cloud infrastructure, making it more likely that we have infrastructure in information/access silos.

If we were able to get a good estimate of cloud compute costs and pass that through to communities as a part of their monthly bill, then this would mean a community like Pangeo could just pay 2i2c entirely for the service, and we could run the infrastructure on a 2i2c cloud project. If this will make it easier for us to skirt around restrictive university email policies, I think that would really help our ability to sustain these kinds of collaborations.

There's a good chance that we'd need to show some extra information about our security / privacy / efficiency practices and such, but that is probably information we'll want to put together anyway for others.

**Comment by rabernat** [comment]
Just chiming in to say that I had a real aha moment when Chris and I briefly discussed this yesterday. So many of the headaches we have faced in working with Columbia are due to the fact that the cloud billing has to go through Columbia. I set this up because I thought (perhaps mistakenly) that 2i2c had no way to cloud provider costs directly through to us, so this was the only way we could pay the cloud bill.

If it is in fact possible for 2i2c to own the billing account for our clusters, that might simplify things a lot (no Columbia UNIs required, no security constraints, etc.) The main uncertainty is what sort of compliance the university might require for a vendor in this category of services. Would they treat it any differently that how 2i2c is treated now?

Technically, the easiest thing to do would be to just create a separate project / billing account for each 2i2c customer. Then you could easily and accurately quantify the costs.

**Comment by choldgraf** [comment]
### Update: will try to work on this soon

@yuvipanda and I chatted about this one today, and agreed that it is an important one to implement in order to be able to send out invoices for our first few batches of communities. So I believe @yuvipanda is going to spend some time thinking this one through, and coordinating with @GeorgianaElena as this is related to the reporting issue she is going to work on as well (https://github.com/2i2c-org/infrastructure/issues/328).

Also updated the top comment with some steps

**Comment by damianavila** [comment]
> The main uncertainty is what sort of compliance the university might require for a vendor in this category of services. 

This is the tricky part, IMHO 😉
But I also expect the benefits outweigh the cons.
Essentially because there might be some big cost at the beginning to be in compliance, but when we get there, that compliance is probably "transferable" to several communities/universities. So we are only paying that cost mostly once!

**Comment by choldgraf** [comment]
### Update: short-term plan

We discussed this in our team meeting today, and are going to plan on a "short term" as well as a "longer term" approach.

**short term**

- For communities that have dedicated cloud resources (e.g., their own Project in Google, or Account in AWS) we can manually look up their cloud costs each month via the UI.
- For communities that have shared cloud resources (on a multi-tenant cloud), we will visually look at the cloud usage over the month, and estimate their cloud bill as a percentage of the cluster's cloud bill.

**long term**

- For all clusters, we'll have a script / job that automatically scrapes our cloud billing data from each cluster for each month.
- For shared clusters, we'll also have a script that examines the Prometheus data for that month, and calculates a per-hub usage percentage, and outputs a "cost per community".

**what we give to CS&S**

In the end, we need to give CS&S a table of "community name / monthly cloud cost" pairs. They will join this with each community's monthly bill, as a separate line item for cloud costs.

- ref: https://github.com/2i2c-org/team-compass/issues/355

**Comment by choldgraf** [comment]
Hey all - I think that we should prioritize getting an MVP of this one working (even if it is just a process for manually looking up cloud costs for each community). However I'm not sure what the right next step should be, I feel like there are two options:

- Define a non-technical process so it's clear who is responsible for calculating the cloud costs for each community, and carry out that process.
- Define a technical solution that automatically does the above.

Do others have suggestions on a path forward here?

**Comment by abkfenris** [comment]
Not that we haven't enjoyed the 'free' hub for OceanHackWeek, but have you explored [KubeCost](https://www.kubecost.com/)/[OpenCost](https://www.opencost.io)?

**Comment by yuvipanda** [comment]
Closing based on https://github.com/2i2c-org/meta/issues/1028#issuecomment-2087793473 and https://github.com/2i2c-org/meta/issues/1028#issuecomment-2089063971
