### ISSUE TITLE
Does our singleuser network policy still make sense?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#829]
I've made a lot of bugfixes to our singleuser network policy in the basehub chart since we closed the original issue. I wanted to check with the team that this still makes sense, all the rules are where they should be, it's maintainable, etc?

https://github.com/2i2c-org/infrastructure/blob/c9efa32c54bb52579833d10a765606b4c405aa67/hub-templates/basehub/values.yaml#L170

related #828

**Comment by sgibson91** [comment]
Ping @2i2c-org/tech-team

**Comment by consideRatio** [comment]
I think it is a bit over the top to limit egress from the user pods from a security perspective, rather than relying on limiting ingress to the locally available network ports.

I don't expect there to much further trouble, but it will remain a complexity to consider even though there isn't additional trouble with this. One must at all times ask oneself "hmmm, is this relying on local network communication, or only public IP based communication?". To answer that can be a bit tricky in general.

I think it is reasonable to:
- _To right now return to the z2jh default and more permissive egress policy_
  Currently only allow the user pods to egress traffic to: non-local IPs and a few exceptions setup for dask-gateway needed communication
- _To retain and evaluate the current configuration a while longer with regards to if its considered worth the maintenance complexity_

I've found working with NetworkPolicies to be the most complicated thing I've done with regards to k8s resources and such. The more anyone needs to learn about this, the more complexity we take on.

I don't want to end up discussing this at length, but my two cents are that it isn't worth the effort to maintain the egress permissions for the user pods specifically.

I think stopping communication from user pods to local network destinations that they shouldn't access still can be accomplished by network policies targeting those destinations with various ingress rules. For example, we already have a rule forbidding anything but the hub pod (which has a certain label) from communicating with the configurable-http-proxy's (in the `proxy` pod) REST API which is exposed on a dedicated port.

**Comment by yuvipanda** [comment]
> I think stopping communication from user pods to local network destinations that they shouldn't access still can be accomplished by network policies targeting those destinations with various ingress rules. For example, we already have a rule forbidding anything but the hub pod (which has a certain label) from communicating with the configurable-http-proxy's (in the `proxy` pod) REST API which is exposed on a dedicated port.

While I generally completely agree 100%, the failure mode here specifically for multi-tenant cases (like the cloudbank or pilot hubs clusters) can be catastrophic (as seen in https://www.wiz.io/blog/chaosdb-explained-azures-cosmos-db-vulnerability-walkthrough). The current policy we have is:

1. Deny *all* private communication
2. Allow specific private communication based on labels

I think with the carve out for talking to other parts of the same hub's infra that we have (nginx-ingress, autohttps, proxy-public), this should be a stable set of possible network pathways for most private communication required from a user pod. This is particularly true because I think most other 'hub services' (like conda-store for example) that might be deployed will go through the network pathways we've laid out already, as they take in traffic via the proxy.

The other issue here is that if we were to try and limit *ingress* for other cluster components, it means we have to properly sort out ingress in a fail-proof way for every component we use. For example, dask-gateway doesn't actually have networkpolicies in it at all, so if we don't limit outbound network from singleuser pods there is no way to restrict traffic to dask-gateway pods right now. While I agree this should be fixed at the dask-gateway level, doing this at the singleuser pod level gives us a lot of control that we won't have otherwise.

I do agree that if this becomes more complicated, we should reevaluate. But as is, I'm pretty happy with the current solution - THANK YOU @sgibson91 and @consideRatio for coming up with that, much cleaner and elegant than the (IMO terrible) port based solution I had come up with earlier.

**Comment by yuvipanda** [comment]
> How would you feel about that?

I'm fairly comfortable with the simplicity of the current solution and the isolation benefit it brings, so it'll have to be drastically simpler for the isolation tradeoff to be worth it :) For example, I consider the fact that a user pod can't access another user pod over the network a feature...

**Comment by consideRatio** [comment]
Ah, but hmmm, maybe we have that already? We can have ingress network policies about that. I think perhaps we do already? I think only hub / proxy can access the user server based on the ingress policy.

**Comment by yuvipanda** [comment]
@consideRatio oops, sorry - poor example :)

I guess what I meant to say was that I'd rather us have a 'deny first' default than an 'allow first' default, even for the local namespace, unless it simplified our current networkpolicy a lot more than it currently is. 

The fundamental lesson in the Azure breach is the lack of defense in depth - they had multiple opportunities to add not-super-highly-complex defenses at many layers, and failed to do so. IMO, network isolation of user provided code is an important layer of defense, and we should make careful tradeoffs here.

I do appreciate that networkpolicies are one of the harder to debug parts of Kubernetes, which is why it's taken a lot of effort on the part of @sgibson91 and @consideRatio to get here, and I do not want to make it more complex than it is now. But blocking outbound traffic via the private IP ranges and then allowing them via labels seems pretty nice to me, but I am open to other tradeoffs if they are radically simpler.

**Comment by yuvipanda** [comment]
Me and @consideRatio had another convesation about this, and here's a summary:

1. We both agree that *restrict all access to internal IPs using this method by default* is a good default for z2jh, and we should consider getting it upstream
2. We currently do not have consensus on wether you should *allow all traffic to pods in the same namespace* or *require any pod that needs to get traffic from a singleuser pod be explicitly labelled*. The second is what we have implemented now.

Is that a fair summary, @consideRatio?

**Comment by sgibson91** [comment]
No clear action point so closing
