### ISSUE TITLE
Explicit path joining in the deployer

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#965]
### Description of problem and opportunity to address it

In the deployer, we have a lot of code that looks like the below:

https://github.com/2i2c-org/infrastructure/blob/f787a914823f49623a6fb410b70f74ad5b910c34/deployer/__main__.py#L30-L32

While I realise _now_ that this is perfectly acceptable syntax, I don't think it's very readable because

- The `/` operator is not behaving how you would expect it to unless you go away and read about the `pathlib.Path` module
- I'm always nervous about hardcoding `/`'s in strings that are to become file paths as it makes assumptions about the OS (even though, in this _specific_ example, `pathlib.Path` accounts for that)

I'm proposing we rewrite the above code to look like:

```python
config_file_path = Path(os.getcwd()).joinpath("config", "hubs", f"{cluster_name}.cluster.yaml")
```

As I believe this is more explicit/readable about what is happening and makes me less nervous about "will the `/` be resolved correctly?"

This is a purely stylistic choice though.

[`joinpath` docs](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.joinpath)

**Comment by consideRatio** [comment]
I've had the same concerns @sgibson91, which merited lookup and thinking through. At the same time, I appreciate onboarding myself to things that are helpful at least if they are part of the standard Python library. So I'm ok with either I think.

Even now after considering this and having learned that you can use `/` with Path objects, I'm not confident about `Path(os.getcwd()) / "config/hubs" / f"{cluster_name}.cluster.yaml"` would work on Windows due to the string literal `"config/hubs"`. Is it okay to combine ahead of time or do you require `"config" / "hubs"` in this situation?

**Comment by sgibson91** [comment]
> Is it okay to combine ahead of time or do you require "config" / "hubs" in this situation?

Since this has been working so far, I'm guessing that "config/hubs" works fine (although, you are right that we have not tested on Windows OS). I guess I'm more after piece of mind than a requirement of sorts.

**Comment by choldgraf** [comment]
+1 from me - I personally like the `/` syntax, but agree that it is more "magical" than doing something explicit like `joinpath`. I'm happy with less magic and more explicit stuff for the team.

**Comment by damianavila** [comment]
💯 on the proposal!
