### ISSUE TITLE
Let the deployer script be a standalone package

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#970]
### Description of problem and opportunity to address it

**Context to understand the problem**

"In the name of R2R" as @sgibson91 said, we should let the deployer script be a standalone module. I figure it should be a python package published to PyPI with changelog and semantic versioned releases etc.

**Problem or idea**

If we do this, we will force ourselves to think of the deployer script as the standalone tool we expect others to use if they decouple with 2i2c. By planning for this, we are way better prepared to help people fly on their own!

**Initial incremental step**
- [x] Make the deployer script a pip installable package within this repo
  See https://github.com/2i2c-org/infrastructure/issues/970#issuecomment-1028004884 by Sarah below
  See https://github.com/2i2c-org/infrastructure/pull/1869

**Proposed solution**

- [ ] We create a repo in 2i2c-org for the deployer script
- [ ] Add pre-commit CI stuff
- [ ] Add a few pytest tests for what is easy to test to start with
- [ ] Add MyST documentation for the project
  - [ ] Include a changelog
- [ ] Cut a release
- [ ] Let's plan for when we release 1.0.0 and make it not be far into the future
  By not getting stuck at 0.X.Y, we can communicate breaking changes a lot easier.

**What's the value and who would benefit**
This would allow users to decouple from 2i2c after a while if they wish and take on the responsibilities themselves, migrating to their standalone management while retaining use of the deployer script if they wish.

**Comment by sgibson91** [comment]
I think a small change we could make even before all that is mentioned here is to add a `setup.py` file to `infrastructure` to make the deployer installable at least. Our invocations would then look something like:

```bash
python setup.py install
deployer deploy ...
```

The `setup.py` file can then be migrated out with the rest of the codebase as and when that action is taken

**Comment by damianavila** [comment]
I like the idea of a standalone package!!

Regarding the setup.py comment @sgibson91 made above, maybe it is time to use new standards such as flit (or some other packaging tool) + pyproject.toml (and no setup.py)?

**Comment by choldgraf** [comment]
Also agree this would be a really nice way to support R2R with our work. A question:

Why wouldn't this just be upstream improvements to `hubploy`? Do we imagine this replacing `hubploy` in the future? I think that this would be particularly impactful if we think that we can *push the boundary* and make something particularly useful for people who are deploying hubs, and not just turn this into a tool purely for 2i2c's R2R purposes. What do others think?

**Comment by sgibson91** [comment]
> maybe it is time to use new standards such as flit (or some other packaging tool) + pyproject.toml (and no setup.py)?

I have never heard of flit before! How new is it? I don't really have experience writing a pyproject.toml file. There's a really good setup.py template [here](https://github.com/kennethreitz/setup.py) that I always reuse as the hard-work has already been done and it "just works".

> Why wouldn't this just be upstream improvements to hubploy?

I guess I haven't used hubploy which is why I didn't immediately think of it. And it's less clear to me what "improvements" would look like there.

I still think it would be beneficial _to us_ to separate out the deployer tool a little more.

**Comment by choldgraf** [comment]
Flit has actually been around for a while - I remember Thomas working on it when I was in grad school like 6 years ago! It recently got moved into the `pypa` organizational account as well, if I recall. It seems to be pretty nice.

Regarding `setup.py`, my understanding is that in general others are nudging the ecosystem towards using `pyproject.toml` in general. For example, the [`pip` docs recommend it, and call `setup.py` "legacy"](https://pip.pypa.io/en/stable/reference/build-system/). So I'd +1 on working towards `pyproject.toml` under the assumption that this will make our tools more in-line with future standards.

> I still think it would be beneficial to us to separate out the deployer tool a little more.

Sounds good - I think if we'd find it useful and it would reduce complexity, that's a good enough reason to do it. It would be a nice added bonus if others could benefit from it as well.

**Comment by sgibson91** [comment]
I think [poetry](https://python-poetry.org/) can be used to generate `pyproject.toml` files and is a tool I've seen presentations/demos on.

**Comment by choldgraf** [comment]
Ah yes I've heard about that one as well, though haven't used either to have strong opinions about it. My understanding is that poetry is often for "application development" where you need to freeze all your package versions etc, whereas `flit` is more for traditional "upload to pypi" workflows. But take everything I say with a grain of salt there :-)

**Comment by sgibson91** [comment]
I believe poetry does both as it has a `build` subcommand to generate wheels.

**Comment by sgibson91** [comment]
The more I dig into the deployer, the more I come to believe that this is not a package anyone outside of the 2i2c Engineering Team will use. It is too specialised towards 1) deploying multiple hubs across many providers, and 2) automating things that an SRE managing so many hubs would not want to do manually because it would take too much time. It's way too complex and overpowered for a single community taking a single hub (maybe two) away from 2i2c. We should instead invest in guidance on how to use their 2i2c config with, e.g., hubploy.

I still believe it will be beneficial _to us_ to have it as a separate, standalone package, but I just don't think we need to be as strict with, say, release cycles since this will be internal to us (but still in a public repository! Just not widely used).

---

On a side-note, I refactored a project of mine to use pyproject.toml using poetry and can confirm that it both manages dependencies as well as builds the packages and publishes it to PyPI. https://github.com/sgibson91/helm-upgrade

**Comment by consideRatio** [comment]
I think the deployer has evolved to be too 2i2c specific at this point for it to be something we turn to if someone exercises the right to replicate.

Since that is the case, I think its not important enough for us to work on decoupling the deployer from this github repo or managing releases.

I'll go for a close on this issue and suggest that a new one is opened with a more specific proposal if there is one part of this issue to pusue still.

**Comment by damianavila** [comment]
I do think there are different levels of the right to replicate exercise... and I can envision how the deployer might be used by others to deploy and manage multiple hubs outside of the 2i2c organization. But I understand that as a secondary or tertiary level so I am OK with this closure and we can evaluate in the future if we need to re-open it (or open a new issue).

**Comment by sgibson91** [comment]
I think one big motivation for moving the deployer into it's own repo, is that we would be able to stop redeploying every hub on every cluster when something under the deployer filepath changes.
